/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_ActuatorSwitch.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// ActuatorSwitchDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ActuatorSwitch.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ActuatorSwitchDataElementsType
    {

        /// <summary>
        /// function
        /// </summary>
        [JsonProperty("function", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Function { get; set; }

    }


    /// <summary>
    /// ActuatorSwitchDataType (SPINE 1.3.0, EEBus_SPINE_TS_ActuatorSwitch.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ActuatorSwitchDataType
    {

        /// <summary>
        /// function
        /// </summary>
        [JsonProperty("function", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ActuatorSwitchFctType? Function { get; set; }

    }


    /// <summary>
    /// ActuatorSwitchDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ActuatorSwitch.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ActuatorSwitchDescriptionDataElementsType
    {

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// ActuatorSwitchDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_ActuatorSwitch.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ActuatorSwitchDescriptionDataType
    {

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public String? Description { get; set; }

    }

}
