/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_BindingManagement.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// BindingManagementDeleteCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementDeleteCallElementsType
    {

        /// <summary>
        /// bindingId
        /// </summary>
        [JsonProperty("bindingId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? BindingId { get; set; }

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressElementsType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureAddressElementsType? ServerAddress { get; set; }

    }


    /// <summary>
    /// BindingManagementDeleteCallType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementDeleteCallType
    {

        /// <summary>
        /// bindingId
        /// </summary>
        [JsonProperty("bindingId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BindingId { get; set; }

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureAddressType? ServerAddress { get; set; }

    }


    /// <summary>
    /// BindingManagementEntryDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementEntryDataElementsType
    {

        /// <summary>
        /// bindingId
        /// </summary>
        [JsonProperty("bindingId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? BindingId { get; set; }

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressElementsType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureAddressElementsType? ServerAddress { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// BindingManagementEntryDataType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementEntryDataType
    {

        /// <summary>
        /// bindingId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("bindingId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BindingId { get; set; }

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureAddressType? ServerAddress { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// BindingManagementEntryListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementEntryListDataSelectorsType
    {

        /// <summary>
        /// bindingId
        /// </summary>
        [JsonProperty("bindingId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BindingId { get; set; }

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureAddressType? ServerAddress { get; set; }

    }


    /// <summary>
    /// BindingManagementEntryListDataType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementEntryListDataType
    {

        /// <summary>
        /// bindingManagementEntryData
        /// </summary>
        [JsonProperty("bindingManagementEntryData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<BindingManagementEntryDataType>? BindingManagementEntryData { get; set; }

    }


    /// <summary>
    /// BindingManagementRequestCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementRequestCallElementsType
    {

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressElementsType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressElementsType? ServerAddress { get; set; }

        /// <summary>
        /// serverFeatureType
        /// </summary>
        [JsonProperty("serverFeatureType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? ServerFeatureType { get; set; }

    }


    /// <summary>
    /// BindingManagementRequestCallType (SPINE 1.3.0, EEBus_SPINE_TS_BindingManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class BindingManagementRequestCallType
    {

        /// <summary>
        /// clientAddress
        /// </summary>
        [JsonProperty("clientAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? ClientAddress { get; set; }

        /// <summary>
        /// serverAddress
        /// </summary>
        [JsonProperty("serverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureAddressType? ServerAddress { get; set; }

        /// <summary>
        /// serverFeatureType
        /// </summary>
        [JsonProperty("serverFeatureType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureTypeType? ServerFeatureType { get; set; }

    }

}
