/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_DeviceDiagnosis.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// DeviceDiagnosisHeartbeatDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class DeviceDiagnosisHeartbeatDataElementsType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// heartbeatCounter
        /// </summary>
        [JsonProperty("heartbeatCounter", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? HeartbeatCounter { get; set; }

        /// <summary>
        /// heartbeatTimeout
        /// </summary>
        [JsonProperty("heartbeatTimeout", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? HeartbeatTimeout { get; set; }

    }


    /// <summary>
    /// DeviceDiagnosisHeartbeatDataType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class DeviceDiagnosisHeartbeatDataType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// heartbeatCounter
        /// </summary>
        [JsonProperty("heartbeatCounter", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt64? HeartbeatCounter { get; set; }

        /// <summary>
        /// heartbeatTimeout
        /// </summary>
        [JsonProperty("heartbeatTimeout", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public DurationType? HeartbeatTimeout { get; set; }

    }


    /// <summary>
    /// DeviceDiagnosisServiceDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class DeviceDiagnosisServiceDataElementsType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// installationTime
        /// </summary>
        [JsonProperty("installationTime", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? InstallationTime { get; set; }

        /// <summary>
        /// bootCounter
        /// </summary>
        [JsonProperty("bootCounter", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? BootCounter { get; set; }

        /// <summary>
        /// nextService
        /// </summary>
        [JsonProperty("nextService", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? NextService { get; set; }

    }


    /// <summary>
    /// DeviceDiagnosisServiceDataType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class DeviceDiagnosisServiceDataType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// installationTime
        /// </summary>
        [JsonProperty("installationTime", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public AbsoluteOrRelativeTimeType? InstallationTime { get; set; }

        /// <summary>
        /// bootCounter
        /// </summary>
        [JsonProperty("bootCounter", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt64? BootCounter { get; set; }

        /// <summary>
        /// nextService
        /// </summary>
        [JsonProperty("nextService", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public AbsoluteOrRelativeTimeType? NextService { get; set; }

    }


    /// <summary>
    /// DeviceDiagnosisStateDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class DeviceDiagnosisStateDataElementsType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// operatingState
        /// </summary>
        [JsonProperty("operatingState", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? OperatingState { get; set; }

        /// <summary>
        /// vendorStateCode
        /// </summary>
        [JsonProperty("vendorStateCode", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? VendorStateCode { get; set; }

        /// <summary>
        /// lastErrorCode
        /// </summary>
        [JsonProperty("lastErrorCode", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? LastErrorCode { get; set; }

        /// <summary>
        /// upTime
        /// </summary>
        [JsonProperty("upTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? UpTime { get; set; }

        /// <summary>
        /// totalUpTime
        /// </summary>
        [JsonProperty("totalUpTime", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? TotalUpTime { get; set; }

        /// <summary>
        /// powerSupplyCondition
        /// </summary>
        [JsonProperty("powerSupplyCondition", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? PowerSupplyCondition { get; set; }

    }


    /// <summary>
    /// DeviceDiagnosisStateDataType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class DeviceDiagnosisStateDataType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// operatingState
        /// </summary>
        [JsonProperty("operatingState", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public DeviceDiagnosisOperatingStateType? OperatingState { get; set; }

        /// <summary>
        /// vendorStateCode
        /// </summary>
        [JsonProperty("vendorStateCode", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public String? VendorStateCode { get; set; }

        /// <summary>
        /// lastErrorCode
        /// </summary>
        [JsonProperty("lastErrorCode", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? LastErrorCode { get; set; }

        /// <summary>
        /// upTime
        /// </summary>
        [JsonProperty("upTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public DurationType? UpTime { get; set; }

        /// <summary>
        /// totalUpTime
        /// </summary>
        [JsonProperty("totalUpTime", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public DurationType? TotalUpTime { get; set; }

        /// <summary>
        /// powerSupplyCondition
        /// </summary>
        [JsonProperty("powerSupplyCondition", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public PowerSupplyConditionType? PowerSupplyCondition { get; set; }

    }

}
