/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_ElectricalConnection.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// ElectricalConnectionCharacteristicDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionCharacteristicDataElementsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ParameterId { get; set; }

        /// <summary>
        /// characteristicId
        /// </summary>
        [JsonProperty("characteristicId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? CharacteristicId { get; set; }

        /// <summary>
        /// characteristicContext
        /// </summary>
        [JsonProperty("characteristicContext", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? CharacteristicContext { get; set; }

        /// <summary>
        /// characteristicType
        /// </summary>
        [JsonProperty("characteristicType", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? CharacteristicType { get; set; }

        /// <summary>
        /// value
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScaledNumberElementsType? Value { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? Unit { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionCharacteristicDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionCharacteristicDataType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ParameterId { get; set; }

        /// <summary>
        /// characteristicId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("characteristicId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? CharacteristicId { get; set; }

        /// <summary>
        /// characteristicContext
        /// </summary>
        [JsonProperty("characteristicContext", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElectricalConnectionCharacteristicContextType? CharacteristicContext { get; set; }

        /// <summary>
        /// characteristicType
        /// </summary>
        [JsonProperty("characteristicType", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElectricalConnectionCharacteristicTypeType? CharacteristicType { get; set; }

        /// <summary>
        /// value
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScaledNumberType? Value { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public UnitOfMeasurementType? Unit { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionCharacteristicListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionCharacteristicListDataSelectorsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ParameterId { get; set; }

        /// <summary>
        /// characteristicId
        /// </summary>
        [JsonProperty("characteristicId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? CharacteristicId { get; set; }

        /// <summary>
        /// characteristicContext
        /// </summary>
        [JsonProperty("characteristicContext", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElectricalConnectionCharacteristicContextType? CharacteristicContext { get; set; }

        /// <summary>
        /// characteristicType
        /// </summary>
        [JsonProperty("characteristicType", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElectricalConnectionCharacteristicTypeType? CharacteristicType { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionCharacteristicListDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionCharacteristicListDataType
    {

        /// <summary>
        /// electricalConnectionCharacteristicData
        /// </summary>
        [JsonProperty("electricalConnectionCharacteristicData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ElectricalConnectionCharacteristicDataType>? ElectricalConnectionCharacteristicData { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionDescriptionDataElementsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ElectricalConnectionId { get; set; }

        /// <summary>
        /// powerSupplyType
        /// </summary>
        [JsonProperty("powerSupplyType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? PowerSupplyType { get; set; }

        /// <summary>
        /// acConnectedPhases
        /// </summary>
        [JsonProperty("acConnectedPhases", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? AcConnectedPhases { get; set; }

        /// <summary>
        /// acRmsPeriodDuration
        /// </summary>
        [JsonProperty("acRmsPeriodDuration", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? AcRmsPeriodDuration { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionDescriptionDataType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// powerSupplyType
        /// </summary>
        [JsonProperty("powerSupplyType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElectricalConnectionVoltageTypeType? PowerSupplyType { get; set; }

        /// <summary>
        /// acConnectedPhases
        /// </summary>
        [JsonProperty("acConnectedPhases", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? AcConnectedPhases { get; set; }

        /// <summary>
        /// acRmsPeriodDuration
        /// </summary>
        [JsonProperty("acRmsPeriodDuration", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public DurationType? AcRmsPeriodDuration { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public EnergyDirectionType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScopeTypeType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionDescriptionListDataSelectorsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScopeTypeType? ScopeType { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionDescriptionListDataType
    {

        /// <summary>
        /// electricalConnectionDescriptionData
        /// </summary>
        [JsonProperty("electricalConnectionDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ElectricalConnectionDescriptionDataType>? ElectricalConnectionDescriptionData { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionParameterDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionParameterDescriptionDataElementsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ParameterId { get; set; }

        /// <summary>
        /// measurementId
        /// </summary>
        [JsonProperty("measurementId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? MeasurementId { get; set; }

        /// <summary>
        /// voltageType
        /// </summary>
        [JsonProperty("voltageType", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? VoltageType { get; set; }

        /// <summary>
        /// acMeasuredPhases
        /// </summary>
        [JsonProperty("acMeasuredPhases", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? AcMeasuredPhases { get; set; }

        /// <summary>
        /// acMeasuredInReferenceTo
        /// </summary>
        [JsonProperty("acMeasuredInReferenceTo", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? AcMeasuredInReferenceTo { get; set; }

        /// <summary>
        /// acMeasurementType
        /// </summary>
        [JsonProperty("acMeasurementType", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? AcMeasurementType { get; set; }

        /// <summary>
        /// acMeasurementVariant
        /// </summary>
        [JsonProperty("acMeasurementVariant", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? AcMeasurementVariant { get; set; }

        /// <summary>
        /// acMeasuredHarmonic
        /// </summary>
        [JsonProperty("acMeasuredHarmonic", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public ElementTagType? AcMeasuredHarmonic { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 10)]
        public ElementTagType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 11)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 12)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionParameterDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionParameterDescriptionDataType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ParameterId { get; set; }

        /// <summary>
        /// measurementId
        /// </summary>
        [JsonProperty("measurementId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? MeasurementId { get; set; }

        /// <summary>
        /// voltageType
        /// </summary>
        [JsonProperty("voltageType", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElectricalConnectionVoltageTypeType? VoltageType { get; set; }

        /// <summary>
        /// acMeasuredPhases
        /// </summary>
        [JsonProperty("acMeasuredPhases", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElectricalConnectionPhaseNameType? AcMeasuredPhases { get; set; }

        /// <summary>
        /// acMeasuredInReferenceTo
        /// </summary>
        [JsonProperty("acMeasuredInReferenceTo", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElectricalConnectionPhaseNameType? AcMeasuredInReferenceTo { get; set; }

        /// <summary>
        /// acMeasurementType
        /// </summary>
        [JsonProperty("acMeasurementType", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElectricalConnectionAcMeasurementTypeType? AcMeasurementType { get; set; }

        /// <summary>
        /// acMeasurementVariant
        /// </summary>
        [JsonProperty("acMeasurementVariant", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElectricalConnectionMeasurandVariantType? AcMeasurementVariant { get; set; }

        /// <summary>
        /// acMeasuredHarmonic
        /// </summary>
        [JsonProperty("acMeasuredHarmonic", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public Byte? AcMeasuredHarmonic { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 10)]
        public ScopeTypeType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 11)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 12)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionParameterDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionParameterDescriptionListDataSelectorsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ParameterId { get; set; }

        /// <summary>
        /// measurementId
        /// </summary>
        [JsonProperty("measurementId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? MeasurementId { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScopeTypeType? ScopeType { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionParameterDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionParameterDescriptionListDataType
    {

        /// <summary>
        /// electricalConnectionParameterDescriptionData
        /// </summary>
        [JsonProperty("electricalConnectionParameterDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ElectricalConnectionParameterDescriptionDataType>? ElectricalConnectionParameterDescriptionData { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionPermittedValueSetDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionPermittedValueSetDataElementsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ParameterId { get; set; }

        /// <summary>
        /// permittedValueSet
        /// </summary>
        [JsonProperty("permittedValueSet", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberSetElementsType? PermittedValueSet { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionPermittedValueSetDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionPermittedValueSetDataType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ParameterId { get; set; }

        /// <summary>
        /// permittedValueSet
        /// </summary>
        [JsonProperty("permittedValueSet", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public List<ScaledNumberSetType>? PermittedValueSet { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionPermittedValueSetListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionPermittedValueSetListDataSelectorsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// parameterId
        /// </summary>
        [JsonProperty("parameterId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ParameterId { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionPermittedValueSetListDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionPermittedValueSetListDataType
    {

        /// <summary>
        /// electricalConnectionPermittedValueSetData
        /// </summary>
        [JsonProperty("electricalConnectionPermittedValueSetData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ElectricalConnectionPermittedValueSetDataType>? ElectricalConnectionPermittedValueSetData { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionStateDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionStateDataElementsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ElectricalConnectionId { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// currentEnergyMode
        /// </summary>
        [JsonProperty("currentEnergyMode", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? CurrentEnergyMode { get; set; }

        /// <summary>
        /// consumptionTime
        /// </summary>
        [JsonProperty("consumptionTime", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? ConsumptionTime { get; set; }

        /// <summary>
        /// productionTime
        /// </summary>
        [JsonProperty("productionTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? ProductionTime { get; set; }

        /// <summary>
        /// totalConsumptionTime
        /// </summary>
        [JsonProperty("totalConsumptionTime", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? TotalConsumptionTime { get; set; }

        /// <summary>
        /// totalProductionTime
        /// </summary>
        [JsonProperty("totalProductionTime", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? TotalProductionTime { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionStateDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionStateDataType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// currentEnergyMode
        /// </summary>
        [JsonProperty("currentEnergyMode", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public EnergyModeType? CurrentEnergyMode { get; set; }

        /// <summary>
        /// consumptionTime
        /// </summary>
        [JsonProperty("consumptionTime", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public DurationType? ConsumptionTime { get; set; }

        /// <summary>
        /// productionTime
        /// </summary>
        [JsonProperty("productionTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public DurationType? ProductionTime { get; set; }

        /// <summary>
        /// totalConsumptionTime
        /// </summary>
        [JsonProperty("totalConsumptionTime", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public DurationType? TotalConsumptionTime { get; set; }

        /// <summary>
        /// totalProductionTime
        /// </summary>
        [JsonProperty("totalProductionTime", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public DurationType? TotalProductionTime { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionStateListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionStateListDataSelectorsType
    {

        /// <summary>
        /// electricalConnectionId
        /// </summary>
        [JsonProperty("electricalConnectionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ElectricalConnectionId { get; set; }

    }


    /// <summary>
    /// ElectricalConnectionStateListDataType (SPINE 1.3.0, EEBus_SPINE_TS_ElectricalConnection.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ElectricalConnectionStateListDataType
    {

        /// <summary>
        /// electricalConnectionStateData
        /// </summary>
        [JsonProperty("electricalConnectionStateData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ElectricalConnectionStateDataType>? ElectricalConnectionStateData { get; set; }

    }

}
