/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_HVAC.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// HvacOperationModeDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOperationModeDescriptionDataElementsType
    {

        /// <summary>
        /// operationModeId
        /// </summary>
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? OperationModeId { get; set; }

        /// <summary>
        /// operationModeType
        /// </summary>
        [JsonProperty("operationModeType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? OperationModeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// HvacOperationModeDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOperationModeDescriptionDataType
    {

        /// <summary>
        /// operationModeId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OperationModeId { get; set; }

        /// <summary>
        /// operationModeType
        /// </summary>
        [JsonProperty("operationModeType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public HvacOperationModeTypeType? OperationModeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// HvacOperationModeDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOperationModeDescriptionListDataSelectorsType
    {

        /// <summary>
        /// operationModeId
        /// </summary>
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OperationModeId { get; set; }

    }


    /// <summary>
    /// HvacOperationModeDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOperationModeDescriptionListDataType
    {

        /// <summary>
        /// hvacOperationModeDescriptionData
        /// </summary>
        [JsonProperty("hvacOperationModeDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacOperationModeDescriptionDataType>? HvacOperationModeDescriptionData { get; set; }

    }


    /// <summary>
    /// HvacOverrunDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunDataElementsType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? OverrunId { get; set; }

        /// <summary>
        /// overrunStatus
        /// </summary>
        [JsonProperty("overrunStatus", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? OverrunStatus { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// isOverrunStatusChangeable
        /// </summary>
        [JsonProperty("isOverrunStatusChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? IsOverrunStatusChangeable { get; set; }

    }


    /// <summary>
    /// HvacOverrunDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunDataType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OverrunId { get; set; }

        /// <summary>
        /// overrunStatus
        /// </summary>
        [JsonProperty("overrunStatus", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public HvacOverrunStatusType? OverrunStatus { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// isOverrunStatusChangeable
        /// </summary>
        [JsonProperty("isOverrunStatusChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public Boolean? IsOverrunStatusChangeable { get; set; }

    }


    /// <summary>
    /// HvacOverrunDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunDescriptionDataElementsType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? OverrunId { get; set; }

        /// <summary>
        /// overrunType
        /// </summary>
        [JsonProperty("overrunType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? OverrunType { get; set; }

        /// <summary>
        /// affectedSystemFunctionId
        /// </summary>
        [JsonProperty("affectedSystemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? AffectedSystemFunctionId { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// HvacOverrunDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunDescriptionDataType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OverrunId { get; set; }

        /// <summary>
        /// overrunType
        /// </summary>
        [JsonProperty("overrunType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public HvacOverrunTypeType? OverrunType { get; set; }

        /// <summary>
        /// affectedSystemFunctionId
        /// </summary>
        [JsonProperty("affectedSystemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public List<UInt32>? AffectedSystemFunctionId { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// HvacOverrunDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunDescriptionListDataSelectorsType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OverrunId { get; set; }

    }


    /// <summary>
    /// HvacOverrunDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunDescriptionListDataType
    {

        /// <summary>
        /// hvacOverrunDescriptionData
        /// </summary>
        [JsonProperty("hvacOverrunDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacOverrunDescriptionDataType>? HvacOverrunDescriptionData { get; set; }

    }


    /// <summary>
    /// HvacOverrunListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunListDataSelectorsType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OverrunId { get; set; }

    }


    /// <summary>
    /// HvacOverrunListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacOverrunListDataType
    {

        /// <summary>
        /// hvacOverrunData
        /// </summary>
        [JsonProperty("hvacOverrunData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacOverrunDataType>? HvacOverrunData { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionDataElementsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SystemFunctionId { get; set; }

        /// <summary>
        /// currentOperationModeId
        /// </summary>
        [JsonProperty("currentOperationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? CurrentOperationModeId { get; set; }

        /// <summary>
        /// isOperationModeIdChangeable
        /// </summary>
        [JsonProperty("isOperationModeIdChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? IsOperationModeIdChangeable { get; set; }

        /// <summary>
        /// currentSetpointId
        /// </summary>
        [JsonProperty("currentSetpointId", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? CurrentSetpointId { get; set; }

        /// <summary>
        /// isSetpointIdChangeable
        /// </summary>
        [JsonProperty("isSetpointIdChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? IsSetpointIdChangeable { get; set; }

        /// <summary>
        /// isOverrunActive
        /// </summary>
        [JsonProperty("isOverrunActive", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? IsOverrunActive { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionDataType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

        /// <summary>
        /// currentOperationModeId
        /// </summary>
        [JsonProperty("currentOperationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? CurrentOperationModeId { get; set; }

        /// <summary>
        /// isOperationModeIdChangeable
        /// </summary>
        [JsonProperty("isOperationModeIdChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public Boolean? IsOperationModeIdChangeable { get; set; }

        /// <summary>
        /// currentSetpointId
        /// </summary>
        [JsonProperty("currentSetpointId", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public UInt32? CurrentSetpointId { get; set; }

        /// <summary>
        /// isSetpointIdChangeable
        /// </summary>
        [JsonProperty("isSetpointIdChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public Boolean? IsSetpointIdChangeable { get; set; }

        /// <summary>
        /// isOverrunActive
        /// </summary>
        [JsonProperty("isOverrunActive", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public Boolean? IsOverrunActive { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionDescriptionDataElementsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SystemFunctionId { get; set; }

        /// <summary>
        /// systemFunctionType
        /// </summary>
        [JsonProperty("systemFunctionType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? SystemFunctionType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionDescriptionDataType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

        /// <summary>
        /// systemFunctionType
        /// </summary>
        [JsonProperty("systemFunctionType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public HvacSystemFunctionTypeType? SystemFunctionType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionDescriptionListDataSelectorsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionDescriptionListDataType
    {

        /// <summary>
        /// hvacSystemFunctionDescriptionData
        /// </summary>
        [JsonProperty("hvacSystemFunctionDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacSystemFunctionDescriptionDataType>? HvacSystemFunctionDescriptionData { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionListDataSelectorsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionListDataType
    {

        /// <summary>
        /// hvacSystemFunctionData
        /// </summary>
        [JsonProperty("hvacSystemFunctionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacSystemFunctionDataType>? HvacSystemFunctionData { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionOperationModeRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionOperationModeRelationDataElementsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SystemFunctionId { get; set; }

        /// <summary>
        /// operationModeId
        /// </summary>
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? OperationModeId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionOperationModeRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionOperationModeRelationDataType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

        /// <summary>
        /// operationModeId
        /// </summary>
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? OperationModeId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionOperationModeRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionOperationModeRelationListDataSelectorsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionOperationModeRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionOperationModeRelationListDataType
    {

        /// <summary>
        /// hvacSystemFunctionOperationModeRelationData
        /// </summary>
        [JsonProperty("hvacSystemFunctionOperationModeRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacSystemFunctionOperationModeRelationDataType>? HvacSystemFunctionOperationModeRelationData { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionPowerSequenceRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionPowerSequenceRelationDataElementsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SystemFunctionId { get; set; }

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? SequenceId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionPowerSequenceRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionPowerSequenceRelationDataType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? SequenceId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionPowerSequenceRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionPowerSequenceRelationListDataSelectorsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionPowerSequenceRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionPowerSequenceRelationListDataType
    {

        /// <summary>
        /// hvacSystemFunctionPowerSequenceRelationData
        /// </summary>
        [JsonProperty("hvacSystemFunctionPowerSequenceRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacSystemFunctionPowerSequenceRelationDataType>? HvacSystemFunctionPowerSequenceRelationData { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionSetpointRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionSetpointRelationDataElementsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SystemFunctionId { get; set; }

        /// <summary>
        /// operationModeId
        /// </summary>
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? OperationModeId { get; set; }

        /// <summary>
        /// setpointId
        /// </summary>
        [JsonProperty("setpointId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? SetpointId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionSetpointRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionSetpointRelationDataType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

        /// <summary>
        /// operationModeId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? OperationModeId { get; set; }

        /// <summary>
        /// setpointId
        /// </summary>
        [JsonProperty("setpointId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public List<UInt32>? SetpointId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionSetpointRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionSetpointRelationListDataSelectorsType
    {

        /// <summary>
        /// systemFunctionId
        /// </summary>
        [JsonProperty("systemFunctionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SystemFunctionId { get; set; }

        /// <summary>
        /// operationModeId
        /// </summary>
        [JsonProperty("operationModeId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? OperationModeId { get; set; }

    }


    /// <summary>
    /// HvacSystemFunctionSetpointRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_HVAC.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class HvacSystemFunctionSetpointRelationListDataType
    {

        /// <summary>
        /// hvacSystemFunctionSetpointRelationData
        /// </summary>
        [JsonProperty("hvacSystemFunctionSetpointRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<HvacSystemFunctionSetpointRelationDataType>? HvacSystemFunctionSetpointRelationData { get; set; }

    }

}
