/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_IncentiveTable.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// IncentiveTableConstraintsDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableConstraintsDataElementsType
    {

        /// <summary>
        /// incentiveTableConstraints
        /// </summary>
        [JsonProperty("incentiveTableConstraints", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public IncentiveTableConstraintsElementsType? IncentiveTableConstraints { get; set; }

    }


    /// <summary>
    /// IncentiveTableConstraintsDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableConstraintsDataSelectorsType
    {

        /// <summary>
        /// tariff
        /// </summary>
        [JsonProperty("tariff", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffListDataSelectorsType? Tariff { get; set; }

    }


    /// <summary>
    /// IncentiveTableConstraintsDataType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableConstraintsDataType
    {

        /// <summary>
        /// incentiveTableConstraints
        /// </summary>
        [JsonProperty("incentiveTableConstraints", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<IncentiveTableConstraintsType>? IncentiveTableConstraints { get; set; }

    }


    /// <summary>
    /// IncentiveTableConstraintsElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableConstraintsElementsType
    {

        /// <summary>
        /// tariff
        /// </summary>
        [JsonProperty("tariff", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDataElementsType? Tariff { get; set; }

        /// <summary>
        /// tariffConstraints
        /// </summary>
        [JsonProperty("tariffConstraints", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TariffOverallConstraintsDataElementsType? TariffConstraints { get; set; }

        /// <summary>
        /// incentiveSlotConstraints
        /// </summary>
        [JsonProperty("incentiveSlotConstraints", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public TimeTableConstraintsDataElementsType? IncentiveSlotConstraints { get; set; }

    }


    /// <summary>
    /// IncentiveTableConstraintsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableConstraintsType
    {

        /// <summary>
        /// tariff
        /// </summary>
        [JsonProperty("tariff", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDataType? Tariff { get; set; }

        /// <summary>
        /// tariffConstraints
        /// </summary>
        [JsonProperty("tariffConstraints", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TariffOverallConstraintsDataType? TariffConstraints { get; set; }

        /// <summary>
        /// incentiveSlotConstraints
        /// </summary>
        [JsonProperty("incentiveSlotConstraints", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public TimeTableConstraintsDataType? IncentiveSlotConstraints { get; set; }

    }


    /// <summary>
    /// IncentiveTableDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDataElementsType
    {

        /// <summary>
        /// incentiveTable
        /// </summary>
        [JsonProperty("incentiveTable", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public IncentiveTableElementsType? IncentiveTable { get; set; }

    }


    /// <summary>
    /// IncentiveTableDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDataSelectorsType
    {

        /// <summary>
        /// tariff
        /// </summary>
        [JsonProperty("tariff", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffListDataSelectorsType? Tariff { get; set; }

    }


    /// <summary>
    /// IncentiveTableDataType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDataType
    {

        /// <summary>
        /// incentiveTable
        /// </summary>
        [JsonProperty("incentiveTable", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<IncentiveTableType>? IncentiveTable { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionDataElementsType
    {

        /// <summary>
        /// incentiveTableDescription
        /// </summary>
        [JsonProperty("incentiveTableDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public IncentiveTableDescriptionElementsType? IncentiveTableDescription { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionDataSelectorsType
    {

        /// <summary>
        /// tariffDescription
        /// </summary>
        [JsonProperty("tariffDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDescriptionListDataSelectorsType? TariffDescription { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionDataType
    {

        /// <summary>
        /// incentiveTableDescription
        /// </summary>
        [JsonProperty("incentiveTableDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<IncentiveTableDescriptionType>? IncentiveTableDescription { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionElementsType
    {

        /// <summary>
        /// tariffDescription
        /// </summary>
        [JsonProperty("tariffDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDescriptionDataElementsType? TariffDescription { get; set; }

        /// <summary>
        /// tier
        /// </summary>
        [JsonProperty("tier", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveTableDescriptionTierElementsType? Tier { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionTierElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionTierElementsType
    {

        /// <summary>
        /// tierDescription
        /// </summary>
        [JsonProperty("tierDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TierDescriptionDataElementsType? TierDescription { get; set; }

        /// <summary>
        /// boundaryDescription
        /// </summary>
        [JsonProperty("boundaryDescription", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TierBoundaryDescriptionDataElementsType? BoundaryDescription { get; set; }

        /// <summary>
        /// incentiveDescription
        /// </summary>
        [JsonProperty("incentiveDescription", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public IncentiveDescriptionDataElementsType? IncentiveDescription { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionTierType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionTierType
    {

        /// <summary>
        /// tierDescription
        /// </summary>
        [JsonProperty("tierDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TierDescriptionDataType? TierDescription { get; set; }

        /// <summary>
        /// boundaryDescription
        /// </summary>
        [JsonProperty("boundaryDescription", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<TierBoundaryDescriptionDataType>? BoundaryDescription { get; set; }

        /// <summary>
        /// incentiveDescription
        /// </summary>
        [JsonProperty("incentiveDescription", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public List<IncentiveDescriptionDataType>? IncentiveDescription { get; set; }

    }


    /// <summary>
    /// IncentiveTableDescriptionType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableDescriptionType
    {

        /// <summary>
        /// tariffDescription
        /// </summary>
        [JsonProperty("tariffDescription", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDescriptionDataType? TariffDescription { get; set; }

        /// <summary>
        /// tier
        /// </summary>
        [JsonProperty("tier", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<IncentiveTableDescriptionTierType>? Tier { get; set; }

    }


    /// <summary>
    /// IncentiveTableElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableElementsType
    {

        /// <summary>
        /// tariff
        /// </summary>
        [JsonProperty("tariff", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDataElementsType? Tariff { get; set; }

        /// <summary>
        /// incentiveSlot
        /// </summary>
        [JsonProperty("incentiveSlot", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveTableIncentiveSlotElementsType? IncentiveSlot { get; set; }

    }


    /// <summary>
    /// IncentiveTableIncentiveSlotElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableIncentiveSlotElementsType
    {

        /// <summary>
        /// timeInterval
        /// </summary>
        [JsonProperty("timeInterval", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TimeTableDataElementsType? TimeInterval { get; set; }

        /// <summary>
        /// tier
        /// </summary>
        [JsonProperty("tier", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveTableTierElementsType? Tier { get; set; }

    }


    /// <summary>
    /// IncentiveTableIncentiveSlotType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableIncentiveSlotType
    {

        /// <summary>
        /// timeInterval
        /// </summary>
        [JsonProperty("timeInterval", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TimeTableDataType? TimeInterval { get; set; }

        /// <summary>
        /// tier
        /// </summary>
        [JsonProperty("tier", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<IncentiveTableTierType>? Tier { get; set; }

    }


    /// <summary>
    /// IncentiveTableTierElementsType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableTierElementsType
    {

        /// <summary>
        /// tier
        /// </summary>
        [JsonProperty("tier", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TierDataElementsType? Tier { get; set; }

        /// <summary>
        /// boundary
        /// </summary>
        [JsonProperty("boundary", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TierBoundaryDataElementsType? Boundary { get; set; }

        /// <summary>
        /// incentive
        /// </summary>
        [JsonProperty("incentive", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public IncentiveDataElementsType? Incentive { get; set; }

    }


    /// <summary>
    /// IncentiveTableTierType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableTierType
    {

        /// <summary>
        /// tier
        /// </summary>
        [JsonProperty("tier", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TierDataType? Tier { get; set; }

        /// <summary>
        /// boundary
        /// </summary>
        [JsonProperty("boundary", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<TierBoundaryDataType>? Boundary { get; set; }

        /// <summary>
        /// incentive
        /// </summary>
        [JsonProperty("incentive", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public List<IncentiveDataType>? Incentive { get; set; }

    }


    /// <summary>
    /// IncentiveTableType (SPINE 1.3.0, EEBus_SPINE_TS_IncentiveTable.xsd).
    /// </summary>
    public class IncentiveTableType
    {

        /// <summary>
        /// tariff
        /// </summary>
        [JsonProperty("tariff", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TariffDataType? Tariff { get; set; }

        /// <summary>
        /// incentiveSlot
        /// </summary>
        [JsonProperty("incentiveSlot", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<IncentiveTableIncentiveSlotType>? IncentiveSlot { get; set; }

    }

}
