/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_NetworkManagement.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// NetworkManagementAbortCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementAbortCallElementsType
    {

    }


    /// <summary>
    /// NetworkManagementAbortCallType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementAbortCallType
    {

    }


    /// <summary>
    /// NetworkManagementAddNodeCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementAddNodeCallElementsType
    {

        /// <summary>
        /// nodeAddress
        /// </summary>
        [JsonProperty("nodeAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressElementsType? NodeAddress { get; set; }

        /// <summary>
        /// nativeSetup
        /// </summary>
        [JsonProperty("nativeSetup", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? NativeSetup { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Timeout { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementAddNodeCallType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementAddNodeCallType
    {

        /// <summary>
        /// nodeAddress
        /// </summary>
        [JsonProperty("nodeAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? NodeAddress { get; set; }

        /// <summary>
        /// nativeSetup
        /// </summary>
        [JsonProperty("nativeSetup", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public String? NativeSetup { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public DurationType? Timeout { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementDeviceDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementDeviceDescriptionDataElementsType
    {

        /// <summary>
        /// deviceAddress
        /// </summary>
        [JsonProperty("deviceAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public DeviceAddressElementsType? DeviceAddress { get; set; }

        /// <summary>
        /// deviceType
        /// </summary>
        [JsonProperty("deviceType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? DeviceType { get; set; }

        /// <summary>
        /// networkManagementResponsibleAddress
        /// </summary>
        [JsonProperty("networkManagementResponsibleAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? NetworkManagementResponsibleAddress { get; set; }

        /// <summary>
        /// nativeSetup
        /// </summary>
        [JsonProperty("nativeSetup", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? NativeSetup { get; set; }

        /// <summary>
        /// technologyAddress
        /// </summary>
        [JsonProperty("technologyAddress", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? TechnologyAddress { get; set; }

        /// <summary>
        /// communicationsTechnologyInformation
        /// </summary>
        [JsonProperty("communicationsTechnologyInformation", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? CommunicationsTechnologyInformation { get; set; }

        /// <summary>
        /// networkFeatureSet
        /// </summary>
        [JsonProperty("networkFeatureSet", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? NetworkFeatureSet { get; set; }

        /// <summary>
        /// lastStateChange
        /// </summary>
        [JsonProperty("lastStateChange", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? LastStateChange { get; set; }

        /// <summary>
        /// minimumTrustLevel
        /// </summary>
        [JsonProperty("minimumTrustLevel", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public ElementTagType? MinimumTrustLevel { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 10)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 11)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementDeviceDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementDeviceDescriptionDataType
    {

        /// <summary>
        /// deviceAddress
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("deviceAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public DeviceAddressType? DeviceAddress { get; set; }

        /// <summary>
        /// deviceType
        /// </summary>
        [JsonProperty("deviceType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public DeviceTypeType? DeviceType { get; set; }

        /// <summary>
        /// networkManagementResponsibleAddress
        /// </summary>
        [JsonProperty("networkManagementResponsibleAddress", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public FeatureAddressType? NetworkManagementResponsibleAddress { get; set; }

        /// <summary>
        /// nativeSetup
        /// </summary>
        [JsonProperty("nativeSetup", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? NativeSetup { get; set; }

        /// <summary>
        /// technologyAddress
        /// </summary>
        [JsonProperty("technologyAddress", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? TechnologyAddress { get; set; }

        /// <summary>
        /// communicationsTechnologyInformation
        /// </summary>
        [JsonProperty("communicationsTechnologyInformation", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public String? CommunicationsTechnologyInformation { get; set; }

        /// <summary>
        /// networkFeatureSet
        /// </summary>
        [JsonProperty("networkFeatureSet", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public NetworkManagementFeatureSetType? NetworkFeatureSet { get; set; }

        /// <summary>
        /// lastStateChange
        /// </summary>
        [JsonProperty("lastStateChange", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public NetworkManagementStateChangeType? LastStateChange { get; set; }

        /// <summary>
        /// minimumTrustLevel
        /// </summary>
        [JsonProperty("minimumTrustLevel", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public String? MinimumTrustLevel { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 10)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 11)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementDeviceDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementDeviceDescriptionListDataSelectorsType
    {

        /// <summary>
        /// deviceAddress
        /// </summary>
        [JsonProperty("deviceAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public DeviceAddressType? DeviceAddress { get; set; }

        /// <summary>
        /// deviceType
        /// </summary>
        [JsonProperty("deviceType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public DeviceTypeType? DeviceType { get; set; }

    }


    /// <summary>
    /// NetworkManagementDeviceDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementDeviceDescriptionListDataType
    {

        /// <summary>
        /// networkManagementDeviceDescriptionData
        /// </summary>
        [JsonProperty("networkManagementDeviceDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<NetworkManagementDeviceDescriptionDataType>? NetworkManagementDeviceDescriptionData { get; set; }

    }


    /// <summary>
    /// NetworkManagementDiscoverCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementDiscoverCallElementsType
    {

        /// <summary>
        /// discoverAddress
        /// </summary>
        [JsonProperty("discoverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressElementsType? DiscoverAddress { get; set; }

    }


    /// <summary>
    /// NetworkManagementDiscoverCallType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementDiscoverCallType
    {

        /// <summary>
        /// discoverAddress
        /// </summary>
        [JsonProperty("discoverAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? DiscoverAddress { get; set; }

    }


    /// <summary>
    /// NetworkManagementEntityDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementEntityDescriptionDataElementsType
    {

        /// <summary>
        /// entityAddress
        /// </summary>
        [JsonProperty("entityAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public EntityAddressElementsType? EntityAddress { get; set; }

        /// <summary>
        /// entityType
        /// </summary>
        [JsonProperty("entityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? EntityType { get; set; }

        /// <summary>
        /// lastStateChange
        /// </summary>
        [JsonProperty("lastStateChange", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? LastStateChange { get; set; }

        /// <summary>
        /// minimumTrustLevel
        /// </summary>
        [JsonProperty("minimumTrustLevel", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? MinimumTrustLevel { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementEntityDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementEntityDescriptionDataType
    {

        /// <summary>
        /// entityAddress
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("entityAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public EntityAddressType? EntityAddress { get; set; }

        /// <summary>
        /// entityType
        /// </summary>
        [JsonProperty("entityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public EntityTypeType? EntityType { get; set; }

        /// <summary>
        /// lastStateChange
        /// </summary>
        [JsonProperty("lastStateChange", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public NetworkManagementStateChangeType? LastStateChange { get; set; }

        /// <summary>
        /// minimumTrustLevel
        /// </summary>
        [JsonProperty("minimumTrustLevel", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? MinimumTrustLevel { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementEntityDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementEntityDescriptionListDataSelectorsType
    {

        /// <summary>
        /// entityAddress
        /// </summary>
        [JsonProperty("entityAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public EntityAddressType? EntityAddress { get; set; }

        /// <summary>
        /// entityType
        /// </summary>
        [JsonProperty("entityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public EntityTypeType? EntityType { get; set; }

    }


    /// <summary>
    /// NetworkManagementEntityDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementEntityDescriptionListDataType
    {

        /// <summary>
        /// networkManagementEntityDescriptionData
        /// </summary>
        [JsonProperty("networkManagementEntityDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<NetworkManagementEntityDescriptionDataType>? NetworkManagementEntityDescriptionData { get; set; }

    }


    /// <summary>
    /// NetworkManagementFeatureDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementFeatureDescriptionDataElementsType
    {

        /// <summary>
        /// featureAddress
        /// </summary>
        [JsonProperty("featureAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressElementsType? FeatureAddress { get; set; }

        /// <summary>
        /// featureType
        /// </summary>
        [JsonProperty("featureType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? FeatureType { get; set; }

        /// <summary>
        /// specificUsage
        /// </summary>
        [JsonProperty("specificUsage", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? SpecificUsage { get; set; }

        /// <summary>
        /// featureGroup
        /// </summary>
        [JsonProperty("featureGroup", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? FeatureGroup { get; set; }

        /// <summary>
        /// role
        /// </summary>
        [JsonProperty("role", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Role { get; set; }

        /// <summary>
        /// supportedFunction
        /// </summary>
        [JsonProperty("supportedFunction", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public FunctionPropertyElementsType? SupportedFunction { get; set; }

        /// <summary>
        /// lastStateChange
        /// </summary>
        [JsonProperty("lastStateChange", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? LastStateChange { get; set; }

        /// <summary>
        /// minimumTrustLevel
        /// </summary>
        [JsonProperty("minimumTrustLevel", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? MinimumTrustLevel { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 10)]
        public ElementTagType? Description { get; set; }

        /// <summary>
        /// maxResponseDelay
        /// </summary>
        [JsonProperty("maxResponseDelay", NullValueHandling = NullValueHandling.Ignore, Order = 11)]
        public ElementTagType? MaxResponseDelay { get; set; }

    }


    /// <summary>
    /// NetworkManagementFeatureDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementFeatureDescriptionDataType
    {

        /// <summary>
        /// featureAddress
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("featureAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? FeatureAddress { get; set; }

        /// <summary>
        /// featureType
        /// </summary>
        [JsonProperty("featureType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureTypeType? FeatureType { get; set; }

        /// <summary>
        /// specificUsage
        /// </summary>
        [JsonProperty("specificUsage", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public List<FeatureSpecificUsageType>? SpecificUsage { get; set; }

        /// <summary>
        /// featureGroup
        /// </summary>
        [JsonProperty("featureGroup", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? FeatureGroup { get; set; }

        /// <summary>
        /// role
        /// </summary>
        [JsonProperty("role", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public RoleType? Role { get; set; }

        /// <summary>
        /// supportedFunction
        /// </summary>
        [JsonProperty("supportedFunction", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public List<FunctionPropertyType>? SupportedFunction { get; set; }

        /// <summary>
        /// lastStateChange
        /// </summary>
        [JsonProperty("lastStateChange", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public NetworkManagementStateChangeType? LastStateChange { get; set; }

        /// <summary>
        /// minimumTrustLevel
        /// </summary>
        [JsonProperty("minimumTrustLevel", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public String? MinimumTrustLevel { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 10)]
        public String? Description { get; set; }

        /// <summary>
        /// maxResponseDelay
        /// </summary>
        [JsonProperty("maxResponseDelay", NullValueHandling = NullValueHandling.Ignore, Order = 11)]
        public DurationType? MaxResponseDelay { get; set; }

    }


    /// <summary>
    /// NetworkManagementFeatureDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementFeatureDescriptionListDataSelectorsType
    {

        /// <summary>
        /// featureAddress
        /// </summary>
        [JsonProperty("featureAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? FeatureAddress { get; set; }

        /// <summary>
        /// featureType
        /// </summary>
        [JsonProperty("featureType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public FeatureTypeType? FeatureType { get; set; }

    }


    /// <summary>
    /// NetworkManagementFeatureDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementFeatureDescriptionListDataType
    {

        /// <summary>
        /// networkManagementFeatureDescriptionData
        /// </summary>
        [JsonProperty("networkManagementFeatureDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<NetworkManagementFeatureDescriptionDataType>? NetworkManagementFeatureDescriptionData { get; set; }

    }


    /// <summary>
    /// NetworkManagementJoiningModeDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementJoiningModeDataElementsType
    {

        /// <summary>
        /// setup
        /// </summary>
        [JsonProperty("setup", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Setup { get; set; }

    }


    /// <summary>
    /// NetworkManagementJoiningModeDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementJoiningModeDataType
    {

        /// <summary>
        /// setup
        /// </summary>
        [JsonProperty("setup", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public String? Setup { get; set; }

    }


    /// <summary>
    /// NetworkManagementModifyNodeCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementModifyNodeCallElementsType
    {

        /// <summary>
        /// nodeAddress
        /// </summary>
        [JsonProperty("nodeAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressElementsType? NodeAddress { get; set; }

        /// <summary>
        /// nativeSetup
        /// </summary>
        [JsonProperty("nativeSetup", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? NativeSetup { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Timeout { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementModifyNodeCallType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementModifyNodeCallType
    {

        /// <summary>
        /// nodeAddress
        /// </summary>
        [JsonProperty("nodeAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? NodeAddress { get; set; }

        /// <summary>
        /// nativeSetup
        /// </summary>
        [JsonProperty("nativeSetup", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public String? NativeSetup { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public DurationType? Timeout { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementProcessStateDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementProcessStateDataElementsType
    {

        /// <summary>
        /// state
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? State { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementProcessStateDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementProcessStateDataType
    {

        /// <summary>
        /// state
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public NetworkManagementProcessStateStateType? State { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementRemoveNodeCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementRemoveNodeCallElementsType
    {

        /// <summary>
        /// nodeAddress
        /// </summary>
        [JsonProperty("nodeAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressElementsType? NodeAddress { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Timeout { get; set; }

    }


    /// <summary>
    /// NetworkManagementRemoveNodeCallType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementRemoveNodeCallType
    {

        /// <summary>
        /// nodeAddress
        /// </summary>
        [JsonProperty("nodeAddress", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public FeatureAddressType? NodeAddress { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public DurationType? Timeout { get; set; }

    }


    /// <summary>
    /// NetworkManagementReportCandidateDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementReportCandidateDataElementsType
    {

        /// <summary>
        /// candidateSetup
        /// </summary>
        [JsonProperty("candidateSetup", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? CandidateSetup { get; set; }

        /// <summary>
        /// setupUsableForAdd
        /// </summary>
        [JsonProperty("setupUsableForAdd", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? SetupUsableForAdd { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementReportCandidateDataType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementReportCandidateDataType
    {

        /// <summary>
        /// candidateSetup
        /// </summary>
        [JsonProperty("candidateSetup", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public String? CandidateSetup { get; set; }

        /// <summary>
        /// setupUsableForAdd
        /// </summary>
        [JsonProperty("setupUsableForAdd", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public Boolean? SetupUsableForAdd { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// NetworkManagementScanNetworkCallElementsType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementScanNetworkCallElementsType
    {

        /// <summary>
        /// scanSetup
        /// </summary>
        [JsonProperty("scanSetup", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ScanSetup { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Timeout { get; set; }

    }


    /// <summary>
    /// NetworkManagementScanNetworkCallType (SPINE 1.3.0, EEBus_SPINE_TS_NetworkManagement.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class NetworkManagementScanNetworkCallType
    {

        /// <summary>
        /// scanSetup
        /// </summary>
        [JsonProperty("scanSetup", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public String? ScanSetup { get; set; }

        /// <summary>
        /// timeout
        /// </summary>
        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public DurationType? Timeout { get; set; }

    }

}
