/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_OperatingConstraints.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// OperatingConstraintsDurationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsDurationDataElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

        /// <summary>
        /// activeDurationMin
        /// </summary>
        [JsonProperty("activeDurationMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ActiveDurationMin { get; set; }

        /// <summary>
        /// activeDurationMax
        /// </summary>
        [JsonProperty("activeDurationMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? ActiveDurationMax { get; set; }

        /// <summary>
        /// pauseDurationMin
        /// </summary>
        [JsonProperty("pauseDurationMin", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? PauseDurationMin { get; set; }

        /// <summary>
        /// pauseDurationMax
        /// </summary>
        [JsonProperty("pauseDurationMax", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? PauseDurationMax { get; set; }

        /// <summary>
        /// activeDurationSumMin
        /// </summary>
        [JsonProperty("activeDurationSumMin", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? ActiveDurationSumMin { get; set; }

        /// <summary>
        /// activeDurationSumMax
        /// </summary>
        [JsonProperty("activeDurationSumMax", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? ActiveDurationSumMax { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsDurationDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsDurationDataType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

        /// <summary>
        /// activeDurationMin
        /// </summary>
        [JsonProperty("activeDurationMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public DurationType? ActiveDurationMin { get; set; }

        /// <summary>
        /// activeDurationMax
        /// </summary>
        [JsonProperty("activeDurationMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public DurationType? ActiveDurationMax { get; set; }

        /// <summary>
        /// pauseDurationMin
        /// </summary>
        [JsonProperty("pauseDurationMin", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public DurationType? PauseDurationMin { get; set; }

        /// <summary>
        /// pauseDurationMax
        /// </summary>
        [JsonProperty("pauseDurationMax", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public DurationType? PauseDurationMax { get; set; }

        /// <summary>
        /// activeDurationSumMin
        /// </summary>
        [JsonProperty("activeDurationSumMin", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public DurationType? ActiveDurationSumMin { get; set; }

        /// <summary>
        /// activeDurationSumMax
        /// </summary>
        [JsonProperty("activeDurationSumMax", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public DurationType? ActiveDurationSumMax { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsDurationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsDurationListDataSelectorsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsDurationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsDurationListDataType
    {

        /// <summary>
        /// operatingConstraintsDurationData
        /// </summary>
        [JsonProperty("operatingConstraintsDurationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<OperatingConstraintsDurationDataType>? OperatingConstraintsDurationData { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsInterruptDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsInterruptDataElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

        /// <summary>
        /// isPausable
        /// </summary>
        [JsonProperty("isPausable", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? IsPausable { get; set; }

        /// <summary>
        /// isStoppable
        /// </summary>
        [JsonProperty("isStoppable", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? IsStoppable { get; set; }

        /// <summary>
        /// notInterruptibleAtHighPower
        /// </summary>
        [JsonProperty("notInterruptibleAtHighPower", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? NotInterruptibleAtHighPower { get; set; }

        /// <summary>
        /// maxCyclesPerDay
        /// </summary>
        [JsonProperty("maxCyclesPerDay", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? MaxCyclesPerDay { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsInterruptDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsInterruptDataType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

        /// <summary>
        /// isPausable
        /// </summary>
        [JsonProperty("isPausable", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public Boolean? IsPausable { get; set; }

        /// <summary>
        /// isStoppable
        /// </summary>
        [JsonProperty("isStoppable", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public Boolean? IsStoppable { get; set; }

        /// <summary>
        /// notInterruptibleAtHighPower
        /// </summary>
        [JsonProperty("notInterruptibleAtHighPower", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public Boolean? NotInterruptibleAtHighPower { get; set; }

        /// <summary>
        /// maxCyclesPerDay
        /// </summary>
        [JsonProperty("maxCyclesPerDay", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public UInt32? MaxCyclesPerDay { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsInterruptListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsInterruptListDataSelectorsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsInterruptListDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsInterruptListDataType
    {

        /// <summary>
        /// operatingConstraintsInterruptData
        /// </summary>
        [JsonProperty("operatingConstraintsInterruptData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<OperatingConstraintsInterruptDataType>? OperatingConstraintsInterruptData { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerDescriptionDataElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// powerUnit
        /// </summary>
        [JsonProperty("powerUnit", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? PowerUnit { get; set; }

        /// <summary>
        /// energyUnit
        /// </summary>
        [JsonProperty("energyUnit", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? EnergyUnit { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerDescriptionDataType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public EnergyDirectionType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// powerUnit
        /// </summary>
        [JsonProperty("powerUnit", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UnitOfMeasurementType? PowerUnit { get; set; }

        /// <summary>
        /// energyUnit
        /// </summary>
        [JsonProperty("energyUnit", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public UnitOfMeasurementType? EnergyUnit { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerDescriptionListDataSelectorsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerDescriptionListDataType
    {

        /// <summary>
        /// operatingConstraintsPowerDescriptionData
        /// </summary>
        [JsonProperty("operatingConstraintsPowerDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<OperatingConstraintsPowerDescriptionDataType>? OperatingConstraintsPowerDescriptionData { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerLevelDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerLevelDataElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

        /// <summary>
        /// power
        /// </summary>
        [JsonProperty("power", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberElementsType? Power { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerLevelDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerLevelDataType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

        /// <summary>
        /// power
        /// </summary>
        [JsonProperty("power", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<ScaledNumberType>? Power { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerLevelListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerLevelListDataSelectorsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerLevelListDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerLevelListDataType
    {

        /// <summary>
        /// operatingConstraintsPowerLevelData
        /// </summary>
        [JsonProperty("operatingConstraintsPowerLevelData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<OperatingConstraintsPowerLevelDataType>? OperatingConstraintsPowerLevelData { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerRangeDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerRangeDataElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

        /// <summary>
        /// powerMin
        /// </summary>
        [JsonProperty("powerMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberElementsType? PowerMin { get; set; }

        /// <summary>
        /// powerMax
        /// </summary>
        [JsonProperty("powerMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberElementsType? PowerMax { get; set; }

        /// <summary>
        /// energyMin
        /// </summary>
        [JsonProperty("energyMin", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberElementsType? EnergyMin { get; set; }

        /// <summary>
        /// energyMax
        /// </summary>
        [JsonProperty("energyMax", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ScaledNumberElementsType? EnergyMax { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerRangeDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerRangeDataType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

        /// <summary>
        /// powerMin
        /// </summary>
        [JsonProperty("powerMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberType? PowerMin { get; set; }

        /// <summary>
        /// powerMax
        /// </summary>
        [JsonProperty("powerMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberType? PowerMax { get; set; }

        /// <summary>
        /// energyMin
        /// </summary>
        [JsonProperty("energyMin", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberType? EnergyMin { get; set; }

        /// <summary>
        /// energyMax
        /// </summary>
        [JsonProperty("energyMax", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ScaledNumberType? EnergyMax { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerRangeListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerRangeListDataSelectorsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsPowerRangeListDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsPowerRangeListDataType
    {

        /// <summary>
        /// operatingConstraintsPowerRangeData
        /// </summary>
        [JsonProperty("operatingConstraintsPowerRangeData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<OperatingConstraintsPowerRangeDataType>? OperatingConstraintsPowerRangeData { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsResumeImplicationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsResumeImplicationDataElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

        /// <summary>
        /// resumeEnergyEstimated
        /// </summary>
        [JsonProperty("resumeEnergyEstimated", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberElementsType? ResumeEnergyEstimated { get; set; }

        /// <summary>
        /// energyUnit
        /// </summary>
        [JsonProperty("energyUnit", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? EnergyUnit { get; set; }

        /// <summary>
        /// resumeCostEstimated
        /// </summary>
        [JsonProperty("resumeCostEstimated", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberElementsType? ResumeCostEstimated { get; set; }

        /// <summary>
        /// currency
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Currency { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsResumeImplicationDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsResumeImplicationDataType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

        /// <summary>
        /// resumeEnergyEstimated
        /// </summary>
        [JsonProperty("resumeEnergyEstimated", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberType? ResumeEnergyEstimated { get; set; }

        /// <summary>
        /// energyUnit
        /// </summary>
        [JsonProperty("energyUnit", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UnitOfMeasurementType? EnergyUnit { get; set; }

        /// <summary>
        /// resumeCostEstimated
        /// </summary>
        [JsonProperty("resumeCostEstimated", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberType? ResumeCostEstimated { get; set; }

        /// <summary>
        /// currency
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public CurrencyType? Currency { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsResumeImplicationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsResumeImplicationListDataSelectorsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// OperatingConstraintsResumeImplicationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_OperatingConstraints.xsd).
    /// </summary>
    public class OperatingConstraintsResumeImplicationListDataType
    {

        /// <summary>
        /// operatingConstraintsResumeImplicationData
        /// </summary>
        [JsonProperty("operatingConstraintsResumeImplicationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<OperatingConstraintsResumeImplicationDataType>? OperatingConstraintsResumeImplicationData { get; set; }

    }

}
