/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_Sensing.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// SensingDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SensingDataElementsType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// state
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? State { get; set; }

        /// <summary>
        /// value
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberElementsType? Value { get; set; }

    }


    /// <summary>
    /// SensingDataType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SensingDataType
    {

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// state
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public SensingStateType? State { get; set; }

        /// <summary>
        /// value
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberType? Value { get; set; }

    }


    /// <summary>
    /// SensingDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SensingDescriptionDataElementsType
    {

        /// <summary>
        /// sensingType
        /// </summary>
        [JsonProperty("sensingType", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SensingType { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Unit { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// SensingDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SensingDescriptionDataType
    {

        /// <summary>
        /// sensingType
        /// </summary>
        [JsonProperty("sensingType", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public SensingTypeType? SensingType { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UnitOfMeasurementType? Unit { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScopeTypeType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// SensingListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SensingListDataSelectorsType
    {

        /// <summary>
        /// timestampInterval
        /// </summary>
        [JsonProperty("timestampInterval", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public TimestampIntervalType? TimestampInterval { get; set; }

    }


    /// <summary>
    /// SensingListDataType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SensingListDataType
    {

        /// <summary>
        /// sensingData
        /// </summary>
        [JsonProperty("sensingData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<SensingDataType>? SensingData { get; set; }

    }

}
