/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_SupplyCondition.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// SupplyConditionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionDataElementsType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ConditionId { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// eventType
        /// </summary>
        [JsonProperty("eventType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? EventType { get; set; }

        /// <summary>
        /// originator
        /// </summary>
        [JsonProperty("originator", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Originator { get; set; }

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? ThresholdId { get; set; }

        /// <summary>
        /// thresholdPercentage
        /// </summary>
        [JsonProperty("thresholdPercentage", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScaledNumberElementsType? ThresholdPercentage { get; set; }

        /// <summary>
        /// relevantPeriod
        /// </summary>
        [JsonProperty("relevantPeriod", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public TimePeriodElementsType? RelevantPeriod { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? Description { get; set; }

        /// <summary>
        /// gridCondition
        /// </summary>
        [JsonProperty("gridCondition", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public ElementTagType? GridCondition { get; set; }

    }


    /// <summary>
    /// SupplyConditionDataType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionDataType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ConditionId { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// eventType
        /// </summary>
        [JsonProperty("eventType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public SupplyConditionEventTypeType? EventType { get; set; }

        /// <summary>
        /// originator
        /// </summary>
        [JsonProperty("originator", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public SupplyConditionOriginatorType? Originator { get; set; }

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public UInt32? ThresholdId { get; set; }

        /// <summary>
        /// thresholdPercentage
        /// </summary>
        [JsonProperty("thresholdPercentage", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScaledNumberType? ThresholdPercentage { get; set; }

        /// <summary>
        /// relevantPeriod
        /// </summary>
        [JsonProperty("relevantPeriod", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public TimePeriodType? RelevantPeriod { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public String? Description { get; set; }

        /// <summary>
        /// gridCondition
        /// </summary>
        [JsonProperty("gridCondition", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public GridConditionType? GridCondition { get; set; }

    }


    /// <summary>
    /// SupplyConditionDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionDescriptionDataElementsType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ConditionId { get; set; }

        /// <summary>
        /// commodityType
        /// </summary>
        [JsonProperty("commodityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? CommodityType { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// SupplyConditionDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionDescriptionDataType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ConditionId { get; set; }

        /// <summary>
        /// commodityType
        /// </summary>
        [JsonProperty("commodityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public CommodityTypeType? CommodityType { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public EnergyDirectionType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// SupplyConditionDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionDescriptionListDataSelectorsType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ConditionId { get; set; }

    }


    /// <summary>
    /// SupplyConditionDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionDescriptionListDataType
    {

        /// <summary>
        /// supplyConditionDescriptionData
        /// </summary>
        [JsonProperty("supplyConditionDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<SupplyConditionDescriptionDataType>? SupplyConditionDescriptionData { get; set; }

    }


    /// <summary>
    /// SupplyConditionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionListDataSelectorsType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ConditionId { get; set; }

        /// <summary>
        /// timestampInterval
        /// </summary>
        [JsonProperty("timestampInterval", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TimestampIntervalType? TimestampInterval { get; set; }

        /// <summary>
        /// eventType
        /// </summary>
        [JsonProperty("eventType", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public SupplyConditionEventTypeType? EventType { get; set; }

        /// <summary>
        /// originator
        /// </summary>
        [JsonProperty("originator", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public SupplyConditionOriginatorType? Originator { get; set; }

    }


    /// <summary>
    /// SupplyConditionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionListDataType
    {

        /// <summary>
        /// supplyConditionData
        /// </summary>
        [JsonProperty("supplyConditionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<SupplyConditionDataType>? SupplyConditionData { get; set; }

    }


    /// <summary>
    /// SupplyConditionThresholdRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionThresholdRelationDataElementsType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ConditionId { get; set; }

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ThresholdId { get; set; }

    }


    /// <summary>
    /// SupplyConditionThresholdRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionThresholdRelationDataType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ConditionId { get; set; }

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? ThresholdId { get; set; }

    }


    /// <summary>
    /// SupplyConditionThresholdRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionThresholdRelationListDataSelectorsType
    {

        /// <summary>
        /// conditionId
        /// </summary>
        [JsonProperty("conditionId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ConditionId { get; set; }

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ThresholdId { get; set; }

    }


    /// <summary>
    /// SupplyConditionThresholdRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_SupplyCondition.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class SupplyConditionThresholdRelationListDataType
    {

        /// <summary>
        /// supplyConditionThresholdRelationData
        /// </summary>
        [JsonProperty("supplyConditionThresholdRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<SupplyConditionThresholdRelationDataType>? SupplyConditionThresholdRelationData { get; set; }

    }

}
