/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_TariffInformation.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// CommodityDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class CommodityDataElementsType
    {

        /// <summary>
        /// commodityId
        /// </summary>
        [JsonProperty("commodityId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? CommodityId { get; set; }

        /// <summary>
        /// commodityType
        /// </summary>
        [JsonProperty("commodityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? CommodityType { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// CommodityDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class CommodityDataType
    {

        /// <summary>
        /// commodityId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("commodityId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? CommodityId { get; set; }

        /// <summary>
        /// commodityType
        /// </summary>
        [JsonProperty("commodityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public CommodityTypeType? CommodityType { get; set; }

        /// <summary>
        /// positiveEnergyDirection
        /// </summary>
        [JsonProperty("positiveEnergyDirection", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public EnergyDirectionType? PositiveEnergyDirection { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// CommodityListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class CommodityListDataSelectorsType
    {

        /// <summary>
        /// commodityId
        /// </summary>
        [JsonProperty("commodityId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? CommodityId { get; set; }

        /// <summary>
        /// commodityType
        /// </summary>
        [JsonProperty("commodityType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public CommodityTypeType? CommodityType { get; set; }

    }


    /// <summary>
    /// CommodityListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class CommodityListDataType
    {

        /// <summary>
        /// commodityData
        /// </summary>
        [JsonProperty("commodityData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<CommodityDataType>? CommodityData { get; set; }

    }


    /// <summary>
    /// IncentiveDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveDataElementsType
    {

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? IncentiveId { get; set; }

        /// <summary>
        /// valueType
        /// </summary>
        [JsonProperty("valueType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ValueType { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// timePeriod
        /// </summary>
        [JsonProperty("timePeriod", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public TimePeriodElementsType? TimePeriod { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// value
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? Value { get; set; }

    }


    /// <summary>
    /// IncentiveDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveDataType
    {

        /// <summary>
        /// incentiveId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? IncentiveId { get; set; }

        /// <summary>
        /// valueType
        /// </summary>
        [JsonProperty("valueType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveValueTypeType? ValueType { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// timePeriod
        /// </summary>
        [JsonProperty("timePeriod", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public TimePeriodType? TimePeriod { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// value
        /// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScaledNumberType? Value { get; set; }

    }


    /// <summary>
    /// IncentiveDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveDescriptionDataElementsType
    {

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? IncentiveId { get; set; }

        /// <summary>
        /// incentiveType
        /// </summary>
        [JsonProperty("incentiveType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? IncentiveType { get; set; }

        /// <summary>
        /// incentivePriority
        /// </summary>
        [JsonProperty("incentivePriority", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? IncentivePriority { get; set; }

        /// <summary>
        /// currency
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Currency { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Unit { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// IncentiveDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveDescriptionDataType
    {

        /// <summary>
        /// incentiveId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? IncentiveId { get; set; }

        /// <summary>
        /// incentiveType
        /// </summary>
        [JsonProperty("incentiveType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveTypeType? IncentiveType { get; set; }

        /// <summary>
        /// incentivePriority
        /// </summary>
        [JsonProperty("incentivePriority", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? IncentivePriority { get; set; }

        /// <summary>
        /// currency
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public CurrencyType? Currency { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public UnitOfMeasurementType? Unit { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// IncentiveDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveDescriptionListDataSelectorsType
    {

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? IncentiveId { get; set; }

        /// <summary>
        /// incentiveType
        /// </summary>
        [JsonProperty("incentiveType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveTypeType? IncentiveType { get; set; }

    }


    /// <summary>
    /// IncentiveDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveDescriptionListDataType
    {

        /// <summary>
        /// incentiveDescriptionData
        /// </summary>
        [JsonProperty("incentiveDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<IncentiveDescriptionDataType>? IncentiveDescriptionData { get; set; }

    }


    /// <summary>
    /// IncentiveListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveListDataSelectorsType
    {

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? IncentiveId { get; set; }

        /// <summary>
        /// valueType
        /// </summary>
        [JsonProperty("valueType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public IncentiveValueTypeType? ValueType { get; set; }

        /// <summary>
        /// timestampInterval
        /// </summary>
        [JsonProperty("timestampInterval", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public TimestampIntervalType? TimestampInterval { get; set; }

    }


    /// <summary>
    /// IncentiveListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class IncentiveListDataType
    {

        /// <summary>
        /// incentiveData
        /// </summary>
        [JsonProperty("incentiveData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<IncentiveDataType>? IncentiveData { get; set; }

    }


    /// <summary>
    /// TariffBoundaryRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffBoundaryRelationDataElementsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TariffId { get; set; }

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? BoundaryId { get; set; }

    }


    /// <summary>
    /// TariffBoundaryRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffBoundaryRelationDataType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? BoundaryId { get; set; }

    }


    /// <summary>
    /// TariffBoundaryRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffBoundaryRelationListDataSelectorsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? BoundaryId { get; set; }

    }


    /// <summary>
    /// TariffBoundaryRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffBoundaryRelationListDataType
    {

        /// <summary>
        /// tariffBoundaryRelationData
        /// </summary>
        [JsonProperty("tariffBoundaryRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TariffBoundaryRelationDataType>? TariffBoundaryRelationData { get; set; }

    }


    /// <summary>
    /// TariffDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffDataElementsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TariffId { get; set; }

        /// <summary>
        /// activeTierId
        /// </summary>
        [JsonProperty("activeTierId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ActiveTierId { get; set; }

    }


    /// <summary>
    /// TariffDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffDataType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// activeTierId
        /// </summary>
        [JsonProperty("activeTierId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? ActiveTierId { get; set; }

    }


    /// <summary>
    /// TariffDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffDescriptionDataElementsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TariffId { get; set; }

        /// <summary>
        /// commodityId
        /// </summary>
        [JsonProperty("commodityId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? CommodityId { get; set; }

        /// <summary>
        /// measurementId
        /// </summary>
        [JsonProperty("measurementId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? MeasurementId { get; set; }

        /// <summary>
        /// tariffWriteable
        /// </summary>
        [JsonProperty("tariffWriteable", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? TariffWriteable { get; set; }

        /// <summary>
        /// updateRequired
        /// </summary>
        [JsonProperty("updateRequired", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? UpdateRequired { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? Description { get; set; }

        /// <summary>
        /// slotIdSupport
        /// </summary>
        [JsonProperty("slotIdSupport", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public ElementTagType? SlotIdSupport { get; set; }

    }


    /// <summary>
    /// TariffDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffDescriptionDataType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// commodityId
        /// </summary>
        [JsonProperty("commodityId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? CommodityId { get; set; }

        /// <summary>
        /// measurementId
        /// </summary>
        [JsonProperty("measurementId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? MeasurementId { get; set; }

        /// <summary>
        /// tariffWriteable
        /// </summary>
        [JsonProperty("tariffWriteable", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public Boolean? TariffWriteable { get; set; }

        /// <summary>
        /// updateRequired
        /// </summary>
        [JsonProperty("updateRequired", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public Boolean? UpdateRequired { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ScopeTypeType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public String? Description { get; set; }

        /// <summary>
        /// slotIdSupport
        /// </summary>
        [JsonProperty("slotIdSupport", NullValueHandling = NullValueHandling.Ignore, Order = 9)]
        public Boolean? SlotIdSupport { get; set; }

    }


    /// <summary>
    /// TariffDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffDescriptionListDataSelectorsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// commodityId
        /// </summary>
        [JsonProperty("commodityId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? CommodityId { get; set; }

        /// <summary>
        /// measurementId
        /// </summary>
        [JsonProperty("measurementId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? MeasurementId { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScopeTypeType? ScopeType { get; set; }

    }


    /// <summary>
    /// TariffDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffDescriptionListDataType
    {

        /// <summary>
        /// tariffDescriptionData
        /// </summary>
        [JsonProperty("tariffDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TariffDescriptionDataType>? TariffDescriptionData { get; set; }

    }


    /// <summary>
    /// TariffListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffListDataSelectorsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// activeTierId
        /// </summary>
        [JsonProperty("activeTierId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ActiveTierId { get; set; }

    }


    /// <summary>
    /// TariffListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffListDataType
    {

        /// <summary>
        /// tariffData
        /// </summary>
        [JsonProperty("tariffData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TariffDataType>? TariffData { get; set; }

    }


    /// <summary>
    /// TariffOverallConstraintsDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffOverallConstraintsDataElementsType
    {

        /// <summary>
        /// maxTariffCount
        /// </summary>
        [JsonProperty("maxTariffCount", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? MaxTariffCount { get; set; }

        /// <summary>
        /// maxBoundaryCount
        /// </summary>
        [JsonProperty("maxBoundaryCount", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? MaxBoundaryCount { get; set; }

        /// <summary>
        /// maxTierCount
        /// </summary>
        [JsonProperty("maxTierCount", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? MaxTierCount { get; set; }

        /// <summary>
        /// maxIncentiveCount
        /// </summary>
        [JsonProperty("maxIncentiveCount", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? MaxIncentiveCount { get; set; }

        /// <summary>
        /// maxBoundariesPerTariff
        /// </summary>
        [JsonProperty("maxBoundariesPerTariff", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? MaxBoundariesPerTariff { get; set; }

        /// <summary>
        /// maxTiersPerTariff
        /// </summary>
        [JsonProperty("maxTiersPerTariff", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? MaxTiersPerTariff { get; set; }

        /// <summary>
        /// maxBoundariesPerTier
        /// </summary>
        [JsonProperty("maxBoundariesPerTier", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? MaxBoundariesPerTier { get; set; }

        /// <summary>
        /// maxIncentivesPerTier
        /// </summary>
        [JsonProperty("maxIncentivesPerTier", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? MaxIncentivesPerTier { get; set; }

    }


    /// <summary>
    /// TariffOverallConstraintsDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffOverallConstraintsDataType
    {

        /// <summary>
        /// maxTariffCount
        /// </summary>
        [JsonProperty("maxTariffCount", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? MaxTariffCount { get; set; }

        /// <summary>
        /// maxBoundaryCount
        /// </summary>
        [JsonProperty("maxBoundaryCount", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? MaxBoundaryCount { get; set; }

        /// <summary>
        /// maxTierCount
        /// </summary>
        [JsonProperty("maxTierCount", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? MaxTierCount { get; set; }

        /// <summary>
        /// maxIncentiveCount
        /// </summary>
        [JsonProperty("maxIncentiveCount", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public UInt32? MaxIncentiveCount { get; set; }

        /// <summary>
        /// maxBoundariesPerTariff
        /// </summary>
        [JsonProperty("maxBoundariesPerTariff", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public UInt32? MaxBoundariesPerTariff { get; set; }

        /// <summary>
        /// maxTiersPerTariff
        /// </summary>
        [JsonProperty("maxTiersPerTariff", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public UInt32? MaxTiersPerTariff { get; set; }

        /// <summary>
        /// maxBoundariesPerTier
        /// </summary>
        [JsonProperty("maxBoundariesPerTier", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public UInt32? MaxBoundariesPerTier { get; set; }

        /// <summary>
        /// maxIncentivesPerTier
        /// </summary>
        [JsonProperty("maxIncentivesPerTier", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public UInt32? MaxIncentivesPerTier { get; set; }

    }


    /// <summary>
    /// TariffTierRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffTierRelationDataElementsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TariffId { get; set; }

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? TierId { get; set; }

    }


    /// <summary>
    /// TariffTierRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffTierRelationDataType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? TierId { get; set; }

    }


    /// <summary>
    /// TariffTierRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffTierRelationListDataSelectorsType
    {

        /// <summary>
        /// tariffId
        /// </summary>
        [JsonProperty("tariffId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TariffId { get; set; }

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? TierId { get; set; }

    }


    /// <summary>
    /// TariffTierRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TariffTierRelationListDataType
    {

        /// <summary>
        /// tariffTierRelationData
        /// </summary>
        [JsonProperty("tariffTierRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TariffTierRelationDataType>? TariffTierRelationData { get; set; }

    }


    /// <summary>
    /// TierBoundaryDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryDataElementsType
    {

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? BoundaryId { get; set; }

        /// <summary>
        /// timePeriod
        /// </summary>
        [JsonProperty("timePeriod", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TimePeriodElementsType? TimePeriod { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// lowerBoundaryValue
        /// </summary>
        [JsonProperty("lowerBoundaryValue", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberElementsType? LowerBoundaryValue { get; set; }

        /// <summary>
        /// upperBoundaryValue
        /// </summary>
        [JsonProperty("upperBoundaryValue", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ScaledNumberElementsType? UpperBoundaryValue { get; set; }

    }


    /// <summary>
    /// TierBoundaryDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryDataType
    {

        /// <summary>
        /// boundaryId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BoundaryId { get; set; }

        /// <summary>
        /// timePeriod
        /// </summary>
        [JsonProperty("timePeriod", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TimePeriodType? TimePeriod { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// lowerBoundaryValue
        /// </summary>
        [JsonProperty("lowerBoundaryValue", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberType? LowerBoundaryValue { get; set; }

        /// <summary>
        /// upperBoundaryValue
        /// </summary>
        [JsonProperty("upperBoundaryValue", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ScaledNumberType? UpperBoundaryValue { get; set; }

    }


    /// <summary>
    /// TierBoundaryDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryDescriptionDataElementsType
    {

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? BoundaryId { get; set; }

        /// <summary>
        /// boundaryType
        /// </summary>
        [JsonProperty("boundaryType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? BoundaryType { get; set; }

        /// <summary>
        /// validForTierId
        /// </summary>
        [JsonProperty("validForTierId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? ValidForTierId { get; set; }

        /// <summary>
        /// switchToTierIdWhenLower
        /// </summary>
        [JsonProperty("switchToTierIdWhenLower", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? SwitchToTierIdWhenLower { get; set; }

        /// <summary>
        /// switchToTierIdWhenHigher
        /// </summary>
        [JsonProperty("switchToTierIdWhenHigher", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? SwitchToTierIdWhenHigher { get; set; }

        /// <summary>
        /// boundaryUnit
        /// </summary>
        [JsonProperty("boundaryUnit", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? BoundaryUnit { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// TierBoundaryDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryDescriptionDataType
    {

        /// <summary>
        /// boundaryId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BoundaryId { get; set; }

        /// <summary>
        /// boundaryType
        /// </summary>
        [JsonProperty("boundaryType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TierBoundaryTypeType? BoundaryType { get; set; }

        /// <summary>
        /// validForTierId
        /// </summary>
        [JsonProperty("validForTierId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? ValidForTierId { get; set; }

        /// <summary>
        /// switchToTierIdWhenLower
        /// </summary>
        [JsonProperty("switchToTierIdWhenLower", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public UInt32? SwitchToTierIdWhenLower { get; set; }

        /// <summary>
        /// switchToTierIdWhenHigher
        /// </summary>
        [JsonProperty("switchToTierIdWhenHigher", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public UInt32? SwitchToTierIdWhenHigher { get; set; }

        /// <summary>
        /// boundaryUnit
        /// </summary>
        [JsonProperty("boundaryUnit", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public UnitOfMeasurementType? BoundaryUnit { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// TierBoundaryDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryDescriptionListDataSelectorsType
    {

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BoundaryId { get; set; }

        /// <summary>
        /// boundaryType
        /// </summary>
        [JsonProperty("boundaryType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TierBoundaryTypeType? BoundaryType { get; set; }

    }


    /// <summary>
    /// TierBoundaryDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryDescriptionListDataType
    {

        /// <summary>
        /// tierBoundaryDescriptionData
        /// </summary>
        [JsonProperty("tierBoundaryDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TierBoundaryDescriptionDataType>? TierBoundaryDescriptionData { get; set; }

    }


    /// <summary>
    /// TierBoundaryListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryListDataSelectorsType
    {

        /// <summary>
        /// boundaryId
        /// </summary>
        [JsonProperty("boundaryId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? BoundaryId { get; set; }

    }


    /// <summary>
    /// TierBoundaryListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierBoundaryListDataType
    {

        /// <summary>
        /// tierBoundaryData
        /// </summary>
        [JsonProperty("tierBoundaryData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TierBoundaryDataType>? TierBoundaryData { get; set; }

    }


    /// <summary>
    /// TierDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierDataElementsType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TierId { get; set; }

        /// <summary>
        /// timePeriod
        /// </summary>
        [JsonProperty("timePeriod", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TimePeriodElementsType? TimePeriod { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// activeIncentiveId
        /// </summary>
        [JsonProperty("activeIncentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? ActiveIncentiveId { get; set; }

    }


    /// <summary>
    /// TierDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierDataType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TierId { get; set; }

        /// <summary>
        /// timePeriod
        /// </summary>
        [JsonProperty("timePeriod", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TimePeriodType? TimePeriod { get; set; }

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// activeIncentiveId
        /// </summary>
        [JsonProperty("activeIncentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public List<UInt32>? ActiveIncentiveId { get; set; }

    }


    /// <summary>
    /// TierDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierDescriptionDataElementsType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TierId { get; set; }

        /// <summary>
        /// tierType
        /// </summary>
        [JsonProperty("tierType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? TierType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// TierDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierDescriptionDataType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TierId { get; set; }

        /// <summary>
        /// tierType
        /// </summary>
        [JsonProperty("tierType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TierTypeType? TierType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// TierDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierDescriptionListDataSelectorsType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TierId { get; set; }

        /// <summary>
        /// tierType
        /// </summary>
        [JsonProperty("tierType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TierTypeType? TierType { get; set; }

    }


    /// <summary>
    /// TierDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierDescriptionListDataType
    {

        /// <summary>
        /// tierDescriptionData
        /// </summary>
        [JsonProperty("tierDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TierDescriptionDataType>? TierDescriptionData { get; set; }

    }


    /// <summary>
    /// TierIncentiveRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierIncentiveRelationDataElementsType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TierId { get; set; }

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? IncentiveId { get; set; }

    }


    /// <summary>
    /// TierIncentiveRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierIncentiveRelationDataType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TierId { get; set; }

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public List<UInt32>? IncentiveId { get; set; }

    }


    /// <summary>
    /// TierIncentiveRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierIncentiveRelationListDataSelectorsType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TierId { get; set; }

        /// <summary>
        /// incentiveId
        /// </summary>
        [JsonProperty("incentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? IncentiveId { get; set; }

    }


    /// <summary>
    /// TierIncentiveRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierIncentiveRelationListDataType
    {

        /// <summary>
        /// tierIncentiveRelationData
        /// </summary>
        [JsonProperty("tierIncentiveRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TierIncentiveRelationDataType>? TierIncentiveRelationData { get; set; }

    }


    /// <summary>
    /// TierListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierListDataSelectorsType
    {

        /// <summary>
        /// tierId
        /// </summary>
        [JsonProperty("tierId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TierId { get; set; }

        /// <summary>
        /// activeIncentiveId
        /// </summary>
        [JsonProperty("activeIncentiveId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? ActiveIncentiveId { get; set; }

    }


    /// <summary>
    /// TierListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TariffInformation.xsd).
    /// </summary>
    public class TierListDataType
    {

        /// <summary>
        /// tierData
        /// </summary>
        [JsonProperty("tierData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TierDataType>? TierData { get; set; }

    }

}
