/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_TaskManagement.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// TaskManagementDirectControlRelatedElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementDirectControlRelatedElementsType
    {

    }


    /// <summary>
    /// TaskManagementDirectControlRelatedType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementDirectControlRelatedType
    {

    }


    /// <summary>
    /// TaskManagementHvacRelatedElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementHvacRelatedElementsType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? OverrunId { get; set; }

    }


    /// <summary>
    /// TaskManagementHvacRelatedType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementHvacRelatedType
    {

        /// <summary>
        /// overrunId
        /// </summary>
        [JsonProperty("overrunId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? OverrunId { get; set; }

    }


    /// <summary>
    /// TaskManagementJobDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobDataElementsType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? JobId { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? Timestamp { get; set; }

        /// <summary>
        /// jobState
        /// </summary>
        [JsonProperty("jobState", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? JobState { get; set; }

        /// <summary>
        /// elapsedTime
        /// </summary>
        [JsonProperty("elapsedTime", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? ElapsedTime { get; set; }

        /// <summary>
        /// remainingTime
        /// </summary>
        [JsonProperty("remainingTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? RemainingTime { get; set; }

    }


    /// <summary>
    /// TaskManagementJobDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobDataType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? JobId { get; set; }

        /// <summary>
        /// timestamp
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public AbsoluteOrRelativeTimeType? Timestamp { get; set; }

        /// <summary>
        /// jobState
        /// </summary>
        [JsonProperty("jobState", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public TaskManagementJobStateType? JobState { get; set; }

        /// <summary>
        /// elapsedTime
        /// </summary>
        [JsonProperty("elapsedTime", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public DurationType? ElapsedTime { get; set; }

        /// <summary>
        /// remainingTime
        /// </summary>
        [JsonProperty("remainingTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public DurationType? RemainingTime { get; set; }

    }


    /// <summary>
    /// TaskManagementJobDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobDescriptionDataElementsType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? JobId { get; set; }

        /// <summary>
        /// jobSource
        /// </summary>
        [JsonProperty("jobSource", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? JobSource { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// TaskManagementJobDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobDescriptionDataType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? JobId { get; set; }

        /// <summary>
        /// jobSource
        /// </summary>
        [JsonProperty("jobSource", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TaskManagementJobSourceType? JobSource { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// TaskManagementJobDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobDescriptionListDataSelectorsType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? JobId { get; set; }

        /// <summary>
        /// jobSource
        /// </summary>
        [JsonProperty("jobSource", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TaskManagementJobSourceType? JobSource { get; set; }

    }


    /// <summary>
    /// TaskManagementJobDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobDescriptionListDataType
    {

        /// <summary>
        /// taskManagementJobDescriptionData
        /// </summary>
        [JsonProperty("taskManagementJobDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TaskManagementJobDescriptionDataType>? TaskManagementJobDescriptionData { get; set; }

    }


    /// <summary>
    /// TaskManagementJobListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobListDataSelectorsType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? JobId { get; set; }

        /// <summary>
        /// jobState
        /// </summary>
        [JsonProperty("jobState", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TaskManagementJobStateType? JobState { get; set; }

    }


    /// <summary>
    /// TaskManagementJobListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobListDataType
    {

        /// <summary>
        /// taskManagementJobData
        /// </summary>
        [JsonProperty("taskManagementJobData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TaskManagementJobDataType>? TaskManagementJobData { get; set; }

    }


    /// <summary>
    /// TaskManagementJobRelationDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobRelationDataElementsType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? JobId { get; set; }

        /// <summary>
        /// directControlRelated
        /// </summary>
        [JsonProperty("directControlRelated", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TaskManagementDirectControlRelatedElementsType? DirectControlRelated { get; set; }

        /// <summary>
        /// hvacRelated
        /// </summary>
        [JsonProperty("hvacRelated", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public TaskManagementHvacRelatedElementsType? HvacRelated { get; set; }

        /// <summary>
        /// loadControlReleated
        /// </summary>
        [JsonProperty("loadControlReleated", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public TaskManagementLoadControlReleatedElementsType? LoadControlReleated { get; set; }

        /// <summary>
        /// powerSequencesRelated
        /// </summary>
        [JsonProperty("powerSequencesRelated", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public TaskManagementPowerSequencesRelatedElementsType? PowerSequencesRelated { get; set; }

        /// <summary>
        /// smartEnergyManagementPsRelated
        /// </summary>
        [JsonProperty("smartEnergyManagementPsRelated", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public TaskManagementSmartEnergyManagementPsRelatedElementsType? SmartEnergyManagementPsRelated { get; set; }

    }


    /// <summary>
    /// TaskManagementJobRelationDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobRelationDataType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? JobId { get; set; }

        /// <summary>
        /// directControlRelated
        /// </summary>
        [JsonProperty("directControlRelated", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public TaskManagementDirectControlRelatedType? DirectControlRelated { get; set; }

        /// <summary>
        /// hvacRelated
        /// </summary>
        [JsonProperty("hvacRelated", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public TaskManagementHvacRelatedType? HvacRelated { get; set; }

        /// <summary>
        /// loadControlReleated
        /// </summary>
        [JsonProperty("loadControlReleated", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public TaskManagementLoadControlReleatedType? LoadControlReleated { get; set; }

        /// <summary>
        /// powerSequencesRelated
        /// </summary>
        [JsonProperty("powerSequencesRelated", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public TaskManagementPowerSequencesRelatedType? PowerSequencesRelated { get; set; }

        /// <summary>
        /// smartEnergyManagementPsRelated
        /// </summary>
        [JsonProperty("smartEnergyManagementPsRelated", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public TaskManagementSmartEnergyManagementPsRelatedType? SmartEnergyManagementPsRelated { get; set; }

    }


    /// <summary>
    /// TaskManagementJobRelationListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobRelationListDataSelectorsType
    {

        /// <summary>
        /// jobId
        /// </summary>
        [JsonProperty("jobId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? JobId { get; set; }

    }


    /// <summary>
    /// TaskManagementJobRelationListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementJobRelationListDataType
    {

        /// <summary>
        /// taskManagementJobRelationData
        /// </summary>
        [JsonProperty("taskManagementJobRelationData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TaskManagementJobRelationDataType>? TaskManagementJobRelationData { get; set; }

    }


    /// <summary>
    /// TaskManagementLoadControlReleatedElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementLoadControlReleatedElementsType
    {

        /// <summary>
        /// eventId
        /// </summary>
        [JsonProperty("eventId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? EventId { get; set; }

    }


    /// <summary>
    /// TaskManagementLoadControlReleatedType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementLoadControlReleatedType
    {

        /// <summary>
        /// eventId
        /// </summary>
        [JsonProperty("eventId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? EventId { get; set; }

    }


    /// <summary>
    /// TaskManagementOverviewDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementOverviewDataElementsType
    {

        /// <summary>
        /// remoteControllable
        /// </summary>
        [JsonProperty("remoteControllable", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? RemoteControllable { get; set; }

        /// <summary>
        /// jobsActive
        /// </summary>
        [JsonProperty("jobsActive", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? JobsActive { get; set; }

    }


    /// <summary>
    /// TaskManagementOverviewDataType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementOverviewDataType
    {

        /// <summary>
        /// remoteControllable
        /// </summary>
        [JsonProperty("remoteControllable", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public Boolean? RemoteControllable { get; set; }

        /// <summary>
        /// jobsActive
        /// </summary>
        [JsonProperty("jobsActive", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public Boolean? JobsActive { get; set; }

    }


    /// <summary>
    /// TaskManagementPowerSequencesRelatedElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementPowerSequencesRelatedElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

    }


    /// <summary>
    /// TaskManagementPowerSequencesRelatedType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementPowerSequencesRelatedType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }


    /// <summary>
    /// TaskManagementSmartEnergyManagementPsRelatedElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementSmartEnergyManagementPsRelatedElementsType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? SequenceId { get; set; }

    }


    /// <summary>
    /// TaskManagementSmartEnergyManagementPsRelatedType (SPINE 1.3.0, EEBus_SPINE_TS_TaskManagement.xsd).
    /// </summary>
    public class TaskManagementSmartEnergyManagementPsRelatedType
    {

        /// <summary>
        /// sequenceId
        /// </summary>
        [JsonProperty("sequenceId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? SequenceId { get; set; }

    }

}
