/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_Threshold.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed, the answer belongs into the
//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,
//     or - for behaviour of a generated type - into its partial class below
//     WWCP_EEBUS_SPINE/Additions/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// ThresholdConstraintsDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdConstraintsDataElementsType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ThresholdId { get; set; }

        /// <summary>
        /// thresholdRangeMin
        /// </summary>
        [JsonProperty("thresholdRangeMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberElementsType? ThresholdRangeMin { get; set; }

        /// <summary>
        /// thresholdRangeMax
        /// </summary>
        [JsonProperty("thresholdRangeMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberElementsType? ThresholdRangeMax { get; set; }

        /// <summary>
        /// thresholdStepSize
        /// </summary>
        [JsonProperty("thresholdStepSize", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberElementsType? ThresholdStepSize { get; set; }

    }


    /// <summary>
    /// ThresholdConstraintsDataType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdConstraintsDataType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ThresholdId { get; set; }

        /// <summary>
        /// thresholdRangeMin
        /// </summary>
        [JsonProperty("thresholdRangeMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberType? ThresholdRangeMin { get; set; }

        /// <summary>
        /// thresholdRangeMax
        /// </summary>
        [JsonProperty("thresholdRangeMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ScaledNumberType? ThresholdRangeMax { get; set; }

        /// <summary>
        /// thresholdStepSize
        /// </summary>
        [JsonProperty("thresholdStepSize", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScaledNumberType? ThresholdStepSize { get; set; }

    }


    /// <summary>
    /// ThresholdConstraintsListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdConstraintsListDataSelectorsType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ThresholdId { get; set; }

    }


    /// <summary>
    /// ThresholdConstraintsListDataType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdConstraintsListDataType
    {

        /// <summary>
        /// thresholdConstraintsData
        /// </summary>
        [JsonProperty("thresholdConstraintsData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ThresholdConstraintsDataType>? ThresholdConstraintsData { get; set; }

    }


    /// <summary>
    /// ThresholdDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdDataElementsType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ThresholdId { get; set; }

        /// <summary>
        /// thresholdValue
        /// </summary>
        [JsonProperty("thresholdValue", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberElementsType? ThresholdValue { get; set; }

    }


    /// <summary>
    /// ThresholdDataType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdDataType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ThresholdId { get; set; }

        /// <summary>
        /// thresholdValue
        /// </summary>
        [JsonProperty("thresholdValue", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScaledNumberType? ThresholdValue { get; set; }

    }


    /// <summary>
    /// ThresholdDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdDescriptionDataElementsType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? ThresholdId { get; set; }

        /// <summary>
        /// thresholdType
        /// </summary>
        [JsonProperty("thresholdType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? ThresholdType { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? Unit { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// ThresholdDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdDescriptionDataType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ThresholdId { get; set; }

        /// <summary>
        /// thresholdType
        /// </summary>
        [JsonProperty("thresholdType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ThresholdTypeType? ThresholdType { get; set; }

        /// <summary>
        /// unit
        /// </summary>
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UnitOfMeasurementType? Unit { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ScopeTypeType? ScopeType { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// ThresholdDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdDescriptionListDataSelectorsType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ThresholdId { get; set; }

        /// <summary>
        /// scopeType
        /// </summary>
        [JsonProperty("scopeType", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ScopeTypeType? ScopeType { get; set; }

    }


    /// <summary>
    /// ThresholdDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdDescriptionListDataType
    {

        /// <summary>
        /// thresholdDescriptionData
        /// </summary>
        [JsonProperty("thresholdDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ThresholdDescriptionDataType>? ThresholdDescriptionData { get; set; }

    }


    /// <summary>
    /// ThresholdListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdListDataSelectorsType
    {

        /// <summary>
        /// thresholdId
        /// </summary>
        [JsonProperty("thresholdId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? ThresholdId { get; set; }

    }


    /// <summary>
    /// ThresholdListDataType (SPINE 1.3.0, EEBus_SPINE_TS_Threshold.xsd).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ThresholdListDataType
    {

        /// <summary>
        /// thresholdData
        /// </summary>
        [JsonProperty("thresholdData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<ThresholdDataType>? ThresholdData { get; set; }

    }

}
