/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     the complex types of EEBus_SPINE_TS_TimeTable.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// TimeTableConstraintsDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableConstraintsDataElementsType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// slotCountMin
        /// </summary>
        [JsonProperty("slotCountMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? SlotCountMin { get; set; }

        /// <summary>
        /// slotCountMax
        /// </summary>
        [JsonProperty("slotCountMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? SlotCountMax { get; set; }

        /// <summary>
        /// slotDurationMin
        /// </summary>
        [JsonProperty("slotDurationMin", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? SlotDurationMin { get; set; }

        /// <summary>
        /// slotDurationMax
        /// </summary>
        [JsonProperty("slotDurationMax", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? SlotDurationMax { get; set; }

        /// <summary>
        /// slotDurationStepSize
        /// </summary>
        [JsonProperty("slotDurationStepSize", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? SlotDurationStepSize { get; set; }

        /// <summary>
        /// slotShiftStepSize
        /// </summary>
        [JsonProperty("slotShiftStepSize", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public ElementTagType? SlotShiftStepSize { get; set; }

        /// <summary>
        /// firstSlotBeginsAt
        /// </summary>
        [JsonProperty("firstSlotBeginsAt", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public ElementTagType? FirstSlotBeginsAt { get; set; }

    }


    /// <summary>
    /// TimeTableConstraintsDataType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableConstraintsDataType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// slotCountMin
        /// </summary>
        [JsonProperty("slotCountMin", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? SlotCountMin { get; set; }

        /// <summary>
        /// slotCountMax
        /// </summary>
        [JsonProperty("slotCountMax", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public UInt32? SlotCountMax { get; set; }

        /// <summary>
        /// slotDurationMin
        /// </summary>
        [JsonProperty("slotDurationMin", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public DurationType? SlotDurationMin { get; set; }

        /// <summary>
        /// slotDurationMax
        /// </summary>
        [JsonProperty("slotDurationMax", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public DurationType? SlotDurationMax { get; set; }

        /// <summary>
        /// slotDurationStepSize
        /// </summary>
        [JsonProperty("slotDurationStepSize", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public DurationType? SlotDurationStepSize { get; set; }

        /// <summary>
        /// slotShiftStepSize
        /// </summary>
        [JsonProperty("slotShiftStepSize", NullValueHandling = NullValueHandling.Ignore, Order = 7)]
        public DurationType? SlotShiftStepSize { get; set; }

        /// <summary>
        /// firstSlotBeginsAt
        /// </summary>
        [JsonProperty("firstSlotBeginsAt", NullValueHandling = NullValueHandling.Ignore, Order = 8)]
        public TimeType? FirstSlotBeginsAt { get; set; }

    }


    /// <summary>
    /// TimeTableConstraintsListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableConstraintsListDataSelectorsType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TimeTableId { get; set; }

    }


    /// <summary>
    /// TimeTableConstraintsListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableConstraintsListDataType
    {

        /// <summary>
        /// timeTableConstraintsData
        /// </summary>
        [JsonProperty("timeTableConstraintsData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TimeTableConstraintsDataType>? TimeTableConstraintsData { get; set; }

    }


    /// <summary>
    /// TimeTableDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableDataElementsType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// timeSlotId
        /// </summary>
        [JsonProperty("timeSlotId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? TimeSlotId { get; set; }

        /// <summary>
        /// recurrenceInformation
        /// </summary>
        [JsonProperty("recurrenceInformation", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public RecurrenceInformationElementsType? RecurrenceInformation { get; set; }

        /// <summary>
        /// startTime
        /// </summary>
        [JsonProperty("startTime", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public AbsoluteOrRecurringTimeElementsType? StartTime { get; set; }

        /// <summary>
        /// endTime
        /// </summary>
        [JsonProperty("endTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public AbsoluteOrRecurringTimeElementsType? EndTime { get; set; }

    }


    /// <summary>
    /// TimeTableDataType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableDataType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// timeSlotId
        /// </summary>
        [EEBUSKey]
        [JsonProperty("timeSlotId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? TimeSlotId { get; set; }

        /// <summary>
        /// recurrenceInformation
        /// </summary>
        [JsonProperty("recurrenceInformation", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public RecurrenceInformationType? RecurrenceInformation { get; set; }

        /// <summary>
        /// startTime
        /// </summary>
        [JsonProperty("startTime", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public AbsoluteOrRecurringTimeType? StartTime { get; set; }

        /// <summary>
        /// endTime
        /// </summary>
        [JsonProperty("endTime", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public AbsoluteOrRecurringTimeType? EndTime { get; set; }

    }


    /// <summary>
    /// TimeTableDescriptionDataElementsType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableDescriptionDataElementsType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public ElementTagType? TimeTableId { get; set; }

        /// <summary>
        /// timeSlotCountChangeable
        /// </summary>
        [JsonProperty("timeSlotCountChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public ElementTagType? TimeSlotCountChangeable { get; set; }

        /// <summary>
        /// timeSlotTimesChangeable
        /// </summary>
        [JsonProperty("timeSlotTimesChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public ElementTagType? TimeSlotTimesChangeable { get; set; }

        /// <summary>
        /// timeSlotTimeMode
        /// </summary>
        [JsonProperty("timeSlotTimeMode", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public ElementTagType? TimeSlotTimeMode { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public ElementTagType? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public ElementTagType? Description { get; set; }

    }


    /// <summary>
    /// TimeTableDescriptionDataType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableDescriptionDataType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [EEBUSKey(IsPrimary: true)]
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// timeSlotCountChangeable
        /// </summary>
        [JsonProperty("timeSlotCountChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public Boolean? TimeSlotCountChangeable { get; set; }

        /// <summary>
        /// timeSlotTimesChangeable
        /// </summary>
        [JsonProperty("timeSlotTimesChangeable", NullValueHandling = NullValueHandling.Ignore, Order = 3)]
        public Boolean? TimeSlotTimesChangeable { get; set; }

        /// <summary>
        /// timeSlotTimeMode
        /// </summary>
        [JsonProperty("timeSlotTimeMode", NullValueHandling = NullValueHandling.Ignore, Order = 4)]
        public TimeSlotTimeModeType? TimeSlotTimeMode { get; set; }

        /// <summary>
        /// label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore, Order = 5)]
        public String? Label { get; set; }

        /// <summary>
        /// description
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore, Order = 6)]
        public String? Description { get; set; }

    }


    /// <summary>
    /// TimeTableDescriptionListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableDescriptionListDataSelectorsType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TimeTableId { get; set; }

    }


    /// <summary>
    /// TimeTableDescriptionListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableDescriptionListDataType
    {

        /// <summary>
        /// timeTableDescriptionData
        /// </summary>
        [JsonProperty("timeTableDescriptionData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TimeTableDescriptionDataType>? TimeTableDescriptionData { get; set; }

    }


    /// <summary>
    /// TimeTableListDataSelectorsType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableListDataSelectorsType
    {

        /// <summary>
        /// timeTableId
        /// </summary>
        [JsonProperty("timeTableId", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public UInt32? TimeTableId { get; set; }

        /// <summary>
        /// timeSlotId
        /// </summary>
        [JsonProperty("timeSlotId", NullValueHandling = NullValueHandling.Ignore, Order = 2)]
        public UInt32? TimeSlotId { get; set; }

    }


    /// <summary>
    /// TimeTableListDataType (SPINE 1.3.0, EEBus_SPINE_TS_TimeTable.xsd).
    /// </summary>
    public class TimeTableListDataType
    {

        /// <summary>
        /// timeTableData
        /// </summary>
        [JsonProperty("timeTableData", NullValueHandling = NullValueHandling.Ignore, Order = 1)]
        public List<TimeTableDataType>? TimeTableData { get; set; }

    }

}
