/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     DeviceDiagnosisOperatingStateType, from EEBus_SPINE_TS_DeviceDiagnosis.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;
using org.GraphDefined.Vanaheimr.Illias;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// Extension methods for DeviceDiagnosisOperatingStateType.
    /// </summary>
    public static class DeviceDiagnosisOperatingStateTypeExtensions
    {

        /// <summary>
        /// Indicates whether this DeviceDiagnosisOperatingStateType is null or empty.
        /// </summary>
        /// <param name="Value">A DeviceDiagnosisOperatingStateType.</param>
        public static Boolean IsNullOrEmpty(this DeviceDiagnosisOperatingStateType? Value)
            => !Value.HasValue || Value.Value.IsNullOrEmpty;

        /// <summary>
        /// Indicates whether this DeviceDiagnosisOperatingStateType is NOT null or empty.
        /// </summary>
        /// <param name="Value">A DeviceDiagnosisOperatingStateType.</param>
        public static Boolean IsNotNullOrEmpty(this DeviceDiagnosisOperatingStateType? Value)
            => Value.HasValue && Value.Value.IsNotNullOrEmpty;

    }


    /// <summary>
    /// DeviceDiagnosisOperatingStateType (SPINE 1.3.0, EEBus_SPINE_TS_DeviceDiagnosis.xsd).
    ///
    /// The specification defines 10 value(s) and unions them with "EnumExtendType",
    /// so a value of a manufacturer is a legal value here.
    ///
    /// Parsing is tolerant either way: a value which the specification does not
    /// define has to survive being received, so that it can be reported. Whether
    /// it is allowed here is decided by the conformance tests, see IsDefined.
    /// </summary>
    [JsonConverter(typeof(SPINEStringTypeConverter<DeviceDiagnosisOperatingStateType>))]
    public readonly struct DeviceDiagnosisOperatingStateType : IId,
                                    ISPINEStringType<DeviceDiagnosisOperatingStateType>,
                                    IEquatable<DeviceDiagnosisOperatingStateType>,
                                    IComparable<DeviceDiagnosisOperatingStateType>
    {

        #region Data

        // Ordinal, not OrdinalIgnoreCase: the values of SPINE are case sensitive.
        // The units of measurement contain both "s" (second) and "S" (siemens).
        private readonly static Dictionary<String, DeviceDiagnosisOperatingStateType>  lookup = new (StringComparer.Ordinal);
        private readonly        String                      InternalId;

        #endregion

        #region Properties

        /// <summary>
        /// Indicates whether this value is null or empty.
        /// </summary>
        public readonly  Boolean  IsNullOrEmpty
            => InternalId.IsNullOrEmpty();

        /// <summary>
        /// Indicates whether this value is NOT null or empty.
        /// </summary>
        public readonly  Boolean  IsNotNullOrEmpty
            => InternalId.IsNotNullOrEmpty();

        /// <summary>
        /// The length of the value.
        /// </summary>
        public readonly  UInt64   Length
            => (UInt64) (InternalId?.Length ?? 0);

        #endregion

        #region Constructor(s)

        private DeviceDiagnosisOperatingStateType(String Text)
        {
            this.InternalId = Text;
        }

        #endregion


        #region (private static) Register(Text)

        private static DeviceDiagnosisOperatingStateType Register(String Text)

            => lookup.AddAndReturnValue(
                   Text,
                   new DeviceDiagnosisOperatingStateType(Text)
               );

        #endregion


        #region (static) Parse   (Text)

        /// <summary>
        /// Parse the given text as a DeviceDiagnosisOperatingStateType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static DeviceDiagnosisOperatingStateType Parse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            throw new ArgumentException("The given text representation of a DeviceDiagnosisOperatingStateType is invalid!",
                                        nameof(Text));

        }

        #endregion

        #region (static) TryParse(Text)

        /// <summary>
        /// Try to parse the given text as a DeviceDiagnosisOperatingStateType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static DeviceDiagnosisOperatingStateType? TryParse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            return null;

        }

        #endregion

        #region (static) TryParse(Text, out Value)

        /// <summary>
        /// Try to parse the given text as a DeviceDiagnosisOperatingStateType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        /// <param name="Value">The parsed value.</param>
        public static Boolean TryParse(String Text, out DeviceDiagnosisOperatingStateType Value)
        {

            Text = Text.Trim();

            if (Text.IsNotNullOrEmpty())
            {

                if (!lookup.TryGetValue(Text, out Value))
                    Value = Register(Text);

                return true;

            }

            Value = default;
            return false;

        }

        #endregion


        #region Static definitions

        /// <summary>
        /// normalOperation
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  NormalOperation   { get; }
            = Register("normalOperation");

        /// <summary>
        /// standby
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  Standby   { get; }
            = Register("standby");

        /// <summary>
        /// failure
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  Failure   { get; }
            = Register("failure");

        /// <summary>
        /// serviceNeeded
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  ServiceNeeded   { get; }
            = Register("serviceNeeded");

        /// <summary>
        /// overrideDetected
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  OverrideDetected   { get; }
            = Register("overrideDetected");

        /// <summary>
        /// inAlarm
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  InAlarm   { get; }
            = Register("inAlarm");

        /// <summary>
        /// notReachable
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  NotReachable   { get; }
            = Register("notReachable");

        /// <summary>
        /// finished
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  Finished   { get; }
            = Register("finished");

        /// <summary>
        /// temporarilyNotReady
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  TemporarilyNotReady   { get; }
            = Register("temporarilyNotReady");

        /// <summary>
        /// off
        /// </summary>
        public static DeviceDiagnosisOperatingStateType  Off   { get; }
            = Register("off");

        #endregion

        #region Validity

        /// <summary>
        /// All values defined by SPINE 1.3.0.
        /// </summary>
        public static IEnumerable<DeviceDiagnosisOperatingStateType>  All    { get; }
            = [
                  NormalOperation,
                  Standby,
                  Failure,
                  ServiceNeeded,
                  OverrideDetected,
                  InAlarm,
                  NotReachable,
                  Finished,
                  TemporarilyNotReady,
                  Off
              ];

        /// <summary>
        /// Whether this is one of the values defined by SPINE 1.3.0.
        /// </summary>
        public Boolean IsDefined
            => All.Contains(this);

        /// <summary>
        /// Whether this enumeration may carry values which the specification does not define.
        /// </summary>
        public static Boolean IsExtensible    { get; }
            = true;

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator == (DeviceDiagnosisOperatingStateType Value1, DeviceDiagnosisOperatingStateType Value2)
            => Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator != (DeviceDiagnosisOperatingStateType Value1, DeviceDiagnosisOperatingStateType Value2)
            => !Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator < (DeviceDiagnosisOperatingStateType Value1, DeviceDiagnosisOperatingStateType Value2)
            => Value1.CompareTo(Value2) <  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator <= (DeviceDiagnosisOperatingStateType Value1, DeviceDiagnosisOperatingStateType Value2)
            => Value1.CompareTo(Value2) <= 0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator > (DeviceDiagnosisOperatingStateType Value1, DeviceDiagnosisOperatingStateType Value2)
            => Value1.CompareTo(Value2) >  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator >= (DeviceDiagnosisOperatingStateType Value1, DeviceDiagnosisOperatingStateType Value2)
            => Value1.CompareTo(Value2) >= 0;

        #endregion

        #region IComparable<DeviceDiagnosisOperatingStateType> Members

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public Int32 CompareTo(Object? Object)

            => Object is DeviceDiagnosisOperatingStateType value
                   ? CompareTo(value)
                   : throw new ArgumentException("The given object is not a DeviceDiagnosisOperatingStateType!",
                                                 nameof(Object));

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Int32 CompareTo(DeviceDiagnosisOperatingStateType Value)

            => String.Compare(InternalId,
                              Value.InternalId,
                              StringComparison.Ordinal);

        #endregion

        #region IEquatable<DeviceDiagnosisOperatingStateType> Members

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public override Boolean Equals(Object? Object)

            => Object is DeviceDiagnosisOperatingStateType value &&
                   Equals(value);

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Boolean Equals(DeviceDiagnosisOperatingStateType Value)

            => String.Equals(InternalId,
                             Value.InternalId,
                             StringComparison.Ordinal);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()

            => InternalId?.GetHashCode() ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return the text representation of this value.
        /// </summary>
        public override String ToString()

            => InternalId ?? "";

        #endregion

    }

}
