/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     FeatureTypeType, from EEBus_SPINE_TS_CommonDataTypes.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;
using org.GraphDefined.Vanaheimr.Illias;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// Extension methods for FeatureTypeType.
    /// </summary>
    public static class FeatureTypeTypeExtensions
    {

        /// <summary>
        /// Indicates whether this FeatureTypeType is null or empty.
        /// </summary>
        /// <param name="Value">A FeatureTypeType.</param>
        public static Boolean IsNullOrEmpty(this FeatureTypeType? Value)
            => !Value.HasValue || Value.Value.IsNullOrEmpty;

        /// <summary>
        /// Indicates whether this FeatureTypeType is NOT null or empty.
        /// </summary>
        /// <param name="Value">A FeatureTypeType.</param>
        public static Boolean IsNotNullOrEmpty(this FeatureTypeType? Value)
            => Value.HasValue && Value.Value.IsNotNullOrEmpty;

    }


    /// <summary>
    /// FeatureTypeType (SPINE 1.3.0, EEBus_SPINE_TS_CommonDataTypes.xsd).
    ///
    /// The specification defines 32 value(s) and unions them with "EnumExtendType",
    /// so a value of a manufacturer is a legal value here.
    ///
    /// Parsing is tolerant either way: a value which the specification does not
    /// define has to survive being received, so that it can be reported. Whether
    /// it is allowed here is decided by the conformance tests, see IsDefined.
    /// </summary>
    [JsonConverter(typeof(SPINEStringTypeConverter<FeatureTypeType>))]
    public readonly struct FeatureTypeType : IId,
                                    ISPINEStringType<FeatureTypeType>,
                                    IEquatable<FeatureTypeType>,
                                    IComparable<FeatureTypeType>
    {

        #region Data

        // Ordinal, not OrdinalIgnoreCase: the values of SPINE are case sensitive.
        // The units of measurement contain both "s" (second) and "S" (siemens).
        private readonly static Dictionary<String, FeatureTypeType>  lookup = new (StringComparer.Ordinal);
        private readonly        String                      InternalId;

        #endregion

        #region Properties

        /// <summary>
        /// Indicates whether this value is null or empty.
        /// </summary>
        public readonly  Boolean  IsNullOrEmpty
            => InternalId.IsNullOrEmpty();

        /// <summary>
        /// Indicates whether this value is NOT null or empty.
        /// </summary>
        public readonly  Boolean  IsNotNullOrEmpty
            => InternalId.IsNotNullOrEmpty();

        /// <summary>
        /// The length of the value.
        /// </summary>
        public readonly  UInt64   Length
            => (UInt64) (InternalId?.Length ?? 0);

        #endregion

        #region Constructor(s)

        private FeatureTypeType(String Text)
        {
            this.InternalId = Text;
        }

        #endregion


        #region (private static) Register(Text)

        private static FeatureTypeType Register(String Text)

            => lookup.AddAndReturnValue(
                   Text,
                   new FeatureTypeType(Text)
               );

        #endregion


        #region (static) Parse   (Text)

        /// <summary>
        /// Parse the given text as a FeatureTypeType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static FeatureTypeType Parse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            throw new ArgumentException("The given text representation of a FeatureTypeType is invalid!",
                                        nameof(Text));

        }

        #endregion

        #region (static) TryParse(Text)

        /// <summary>
        /// Try to parse the given text as a FeatureTypeType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static FeatureTypeType? TryParse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            return null;

        }

        #endregion

        #region (static) TryParse(Text, out Value)

        /// <summary>
        /// Try to parse the given text as a FeatureTypeType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        /// <param name="Value">The parsed value.</param>
        public static Boolean TryParse(String Text, out FeatureTypeType Value)
        {

            Text = Text.Trim();

            if (Text.IsNotNullOrEmpty())
            {

                if (!lookup.TryGetValue(Text, out Value))
                    Value = Register(Text);

                return true;

            }

            Value = default;
            return false;

        }

        #endregion


        #region Static definitions

        /// <summary>
        /// ActuatorLevel
        /// </summary>
        public static FeatureTypeType  ActuatorLevel   { get; }
            = Register("ActuatorLevel");

        /// <summary>
        /// ActuatorSwitch
        /// </summary>
        public static FeatureTypeType  ActuatorSwitch   { get; }
            = Register("ActuatorSwitch");

        /// <summary>
        /// Alarm
        /// </summary>
        public static FeatureTypeType  Alarm   { get; }
            = Register("Alarm");

        /// <summary>
        /// DataTunneling
        /// </summary>
        public static FeatureTypeType  DataTunneling   { get; }
            = Register("DataTunneling");

        /// <summary>
        /// DeviceClassification
        /// </summary>
        public static FeatureTypeType  DeviceClassification   { get; }
            = Register("DeviceClassification");

        /// <summary>
        /// DeviceDiagnosis
        /// </summary>
        public static FeatureTypeType  DeviceDiagnosis   { get; }
            = Register("DeviceDiagnosis");

        /// <summary>
        /// DirectControl
        /// </summary>
        public static FeatureTypeType  DirectControl   { get; }
            = Register("DirectControl");

        /// <summary>
        /// ElectricalConnection
        /// </summary>
        public static FeatureTypeType  ElectricalConnection   { get; }
            = Register("ElectricalConnection");

        /// <summary>
        /// Generic
        /// </summary>
        public static FeatureTypeType  Generic   { get; }
            = Register("Generic");

        /// <summary>
        /// HVAC
        /// </summary>
        public static FeatureTypeType  HVAC   { get; }
            = Register("HVAC");

        /// <summary>
        /// LoadControl
        /// </summary>
        public static FeatureTypeType  LoadControl   { get; }
            = Register("LoadControl");

        /// <summary>
        /// Measurement
        /// </summary>
        public static FeatureTypeType  Measurement   { get; }
            = Register("Measurement");

        /// <summary>
        /// Messaging
        /// </summary>
        public static FeatureTypeType  Messaging   { get; }
            = Register("Messaging");

        /// <summary>
        /// NetworkManagement
        /// </summary>
        public static FeatureTypeType  NetworkManagement   { get; }
            = Register("NetworkManagement");

        /// <summary>
        /// NodeManagement
        /// </summary>
        public static FeatureTypeType  NodeManagement   { get; }
            = Register("NodeManagement");

        /// <summary>
        /// OperatingConstraints
        /// </summary>
        public static FeatureTypeType  OperatingConstraints   { get; }
            = Register("OperatingConstraints");

        /// <summary>
        /// PowerSequences
        /// </summary>
        public static FeatureTypeType  PowerSequences   { get; }
            = Register("PowerSequences");

        /// <summary>
        /// Sensing
        /// </summary>
        public static FeatureTypeType  Sensing   { get; }
            = Register("Sensing");

        /// <summary>
        /// Setpoint
        /// </summary>
        public static FeatureTypeType  Setpoint   { get; }
            = Register("Setpoint");

        /// <summary>
        /// SmartEnergyManagementPs
        /// </summary>
        public static FeatureTypeType  SmartEnergyManagementPs   { get; }
            = Register("SmartEnergyManagementPs");

        /// <summary>
        /// TaskManagement
        /// </summary>
        public static FeatureTypeType  TaskManagement   { get; }
            = Register("TaskManagement");

        /// <summary>
        /// Threshold
        /// </summary>
        public static FeatureTypeType  Threshold   { get; }
            = Register("Threshold");

        /// <summary>
        /// TimeInformation
        /// </summary>
        public static FeatureTypeType  TimeInformation   { get; }
            = Register("TimeInformation");

        /// <summary>
        /// TimeTable
        /// </summary>
        public static FeatureTypeType  TimeTable   { get; }
            = Register("TimeTable");

        /// <summary>
        /// DeviceConfiguration
        /// </summary>
        public static FeatureTypeType  DeviceConfiguration   { get; }
            = Register("DeviceConfiguration");

        /// <summary>
        /// SupplyCondition
        /// </summary>
        public static FeatureTypeType  SupplyCondition   { get; }
            = Register("SupplyCondition");

        /// <summary>
        /// TimeSeries
        /// </summary>
        public static FeatureTypeType  TimeSeries   { get; }
            = Register("TimeSeries");

        /// <summary>
        /// TariffInformation
        /// </summary>
        public static FeatureTypeType  TariffInformation   { get; }
            = Register("TariffInformation");

        /// <summary>
        /// IncentiveTable
        /// </summary>
        public static FeatureTypeType  IncentiveTable   { get; }
            = Register("IncentiveTable");

        /// <summary>
        /// Bill
        /// </summary>
        public static FeatureTypeType  Bill   { get; }
            = Register("Bill");

        /// <summary>
        /// Identification
        /// </summary>
        public static FeatureTypeType  Identification   { get; }
            = Register("Identification");

        /// <summary>
        /// StateInformation
        /// </summary>
        public static FeatureTypeType  StateInformation   { get; }
            = Register("StateInformation");

        #endregion

        #region Validity

        /// <summary>
        /// All values defined by SPINE 1.3.0.
        /// </summary>
        public static IEnumerable<FeatureTypeType>  All    { get; }
            = [
                  ActuatorLevel,
                  ActuatorSwitch,
                  Alarm,
                  DataTunneling,
                  DeviceClassification,
                  DeviceDiagnosis,
                  DirectControl,
                  ElectricalConnection,
                  Generic,
                  HVAC,
                  LoadControl,
                  Measurement,
                  Messaging,
                  NetworkManagement,
                  NodeManagement,
                  OperatingConstraints,
                  PowerSequences,
                  Sensing,
                  Setpoint,
                  SmartEnergyManagementPs,
                  TaskManagement,
                  Threshold,
                  TimeInformation,
                  TimeTable,
                  DeviceConfiguration,
                  SupplyCondition,
                  TimeSeries,
                  TariffInformation,
                  IncentiveTable,
                  Bill,
                  Identification,
                  StateInformation
              ];

        /// <summary>
        /// Whether this is one of the values defined by SPINE 1.3.0.
        /// </summary>
        public Boolean IsDefined
            => All.Contains(this);

        /// <summary>
        /// Whether this enumeration may carry values which the specification does not define.
        /// </summary>
        public static Boolean IsExtensible    { get; }
            = true;

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator == (FeatureTypeType Value1, FeatureTypeType Value2)
            => Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator != (FeatureTypeType Value1, FeatureTypeType Value2)
            => !Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator < (FeatureTypeType Value1, FeatureTypeType Value2)
            => Value1.CompareTo(Value2) <  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator <= (FeatureTypeType Value1, FeatureTypeType Value2)
            => Value1.CompareTo(Value2) <= 0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator > (FeatureTypeType Value1, FeatureTypeType Value2)
            => Value1.CompareTo(Value2) >  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator >= (FeatureTypeType Value1, FeatureTypeType Value2)
            => Value1.CompareTo(Value2) >= 0;

        #endregion

        #region IComparable<FeatureTypeType> Members

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public Int32 CompareTo(Object? Object)

            => Object is FeatureTypeType value
                   ? CompareTo(value)
                   : throw new ArgumentException("The given object is not a FeatureTypeType!",
                                                 nameof(Object));

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Int32 CompareTo(FeatureTypeType Value)

            => String.Compare(InternalId,
                              Value.InternalId,
                              StringComparison.Ordinal);

        #endregion

        #region IEquatable<FeatureTypeType> Members

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public override Boolean Equals(Object? Object)

            => Object is FeatureTypeType value &&
                   Equals(value);

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Boolean Equals(FeatureTypeType Value)

            => String.Equals(InternalId,
                             Value.InternalId,
                             StringComparison.Ordinal);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()

            => InternalId?.GetHashCode() ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return the text representation of this value.
        /// </summary>
        public override String ToString()

            => InternalId ?? "";

        #endregion

    }

}
