/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     FunctionType, from EEBus_SPINE_TS_CommonDataTypes.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;
using org.GraphDefined.Vanaheimr.Illias;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// Extension methods for FunctionType.
    /// </summary>
    public static class FunctionTypeExtensions
    {

        /// <summary>
        /// Indicates whether this FunctionType is null or empty.
        /// </summary>
        /// <param name="Value">A FunctionType.</param>
        public static Boolean IsNullOrEmpty(this FunctionType? Value)
            => !Value.HasValue || Value.Value.IsNullOrEmpty;

        /// <summary>
        /// Indicates whether this FunctionType is NOT null or empty.
        /// </summary>
        /// <param name="Value">A FunctionType.</param>
        public static Boolean IsNotNullOrEmpty(this FunctionType? Value)
            => Value.HasValue && Value.Value.IsNotNullOrEmpty;

    }


    /// <summary>
    /// FunctionType (SPINE 1.3.0, EEBus_SPINE_TS_CommonDataTypes.xsd).
    ///
    /// The specification defines 142 value(s) and unions them with "EnumExtendType",
    /// so a value of a manufacturer is a legal value here.
    ///
    /// Parsing is tolerant either way: a value which the specification does not
    /// define has to survive being received, so that it can be reported. Whether
    /// it is allowed here is decided by the conformance tests, see IsDefined.
    /// </summary>
    [JsonConverter(typeof(SPINEStringTypeConverter<FunctionType>))]
    public readonly struct FunctionType : IId,
                                    ISPINEStringType<FunctionType>,
                                    IEquatable<FunctionType>,
                                    IComparable<FunctionType>
    {

        #region Data

        // Ordinal, not OrdinalIgnoreCase: the values of SPINE are case sensitive.
        // The units of measurement contain both "s" (second) and "S" (siemens).
        private readonly static Dictionary<String, FunctionType>  lookup = new (StringComparer.Ordinal);
        private readonly        String                      InternalId;

        #endregion

        #region Properties

        /// <summary>
        /// Indicates whether this value is null or empty.
        /// </summary>
        public readonly  Boolean  IsNullOrEmpty
            => InternalId.IsNullOrEmpty();

        /// <summary>
        /// Indicates whether this value is NOT null or empty.
        /// </summary>
        public readonly  Boolean  IsNotNullOrEmpty
            => InternalId.IsNotNullOrEmpty();

        /// <summary>
        /// The length of the value.
        /// </summary>
        public readonly  UInt64   Length
            => (UInt64) (InternalId?.Length ?? 0);

        #endregion

        #region Constructor(s)

        private FunctionType(String Text)
        {
            this.InternalId = Text;
        }

        #endregion


        #region (private static) Register(Text)

        private static FunctionType Register(String Text)

            => lookup.AddAndReturnValue(
                   Text,
                   new FunctionType(Text)
               );

        #endregion


        #region (static) Parse   (Text)

        /// <summary>
        /// Parse the given text as a FunctionType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static FunctionType Parse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            throw new ArgumentException("The given text representation of a FunctionType is invalid!",
                                        nameof(Text));

        }

        #endregion

        #region (static) TryParse(Text)

        /// <summary>
        /// Try to parse the given text as a FunctionType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static FunctionType? TryParse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            return null;

        }

        #endregion

        #region (static) TryParse(Text, out Value)

        /// <summary>
        /// Try to parse the given text as a FunctionType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        /// <param name="Value">The parsed value.</param>
        public static Boolean TryParse(String Text, out FunctionType Value)
        {

            Text = Text.Trim();

            if (Text.IsNotNullOrEmpty())
            {

                if (!lookup.TryGetValue(Text, out Value))
                    Value = Register(Text);

                return true;

            }

            Value = default;
            return false;

        }

        #endregion


        #region Static definitions

        /// <summary>
        /// actuatorLevelData
        /// </summary>
        public static FunctionType  ActuatorLevelData   { get; }
            = Register("actuatorLevelData");

        /// <summary>
        /// actuatorLevelDescriptionData
        /// </summary>
        public static FunctionType  ActuatorLevelDescriptionData   { get; }
            = Register("actuatorLevelDescriptionData");

        /// <summary>
        /// actuatorSwitchData
        /// </summary>
        public static FunctionType  ActuatorSwitchData   { get; }
            = Register("actuatorSwitchData");

        /// <summary>
        /// actuatorSwitchDescriptionData
        /// </summary>
        public static FunctionType  ActuatorSwitchDescriptionData   { get; }
            = Register("actuatorSwitchDescriptionData");

        /// <summary>
        /// alarmListData
        /// </summary>
        public static FunctionType  AlarmListData   { get; }
            = Register("alarmListData");

        /// <summary>
        /// bindingManagementDeleteCall
        /// </summary>
        public static FunctionType  BindingManagementDeleteCall   { get; }
            = Register("bindingManagementDeleteCall");

        /// <summary>
        /// bindingManagementEntryListData
        /// </summary>
        public static FunctionType  BindingManagementEntryListData   { get; }
            = Register("bindingManagementEntryListData");

        /// <summary>
        /// bindingManagementRequestCall
        /// </summary>
        public static FunctionType  BindingManagementRequestCall   { get; }
            = Register("bindingManagementRequestCall");

        /// <summary>
        /// dataTunnelingCall
        /// </summary>
        public static FunctionType  DataTunnelingCall   { get; }
            = Register("dataTunnelingCall");

        /// <summary>
        /// deviceClassificationManufacturerData
        /// </summary>
        public static FunctionType  DeviceClassificationManufacturerData   { get; }
            = Register("deviceClassificationManufacturerData");

        /// <summary>
        /// deviceClassificationUserData
        /// </summary>
        public static FunctionType  DeviceClassificationUserData   { get; }
            = Register("deviceClassificationUserData");

        /// <summary>
        /// deviceDiagnosisHeartbeatData
        /// </summary>
        public static FunctionType  DeviceDiagnosisHeartbeatData   { get; }
            = Register("deviceDiagnosisHeartbeatData");

        /// <summary>
        /// deviceDiagnosisServiceData
        /// </summary>
        public static FunctionType  DeviceDiagnosisServiceData   { get; }
            = Register("deviceDiagnosisServiceData");

        /// <summary>
        /// deviceDiagnosisStateData
        /// </summary>
        public static FunctionType  DeviceDiagnosisStateData   { get; }
            = Register("deviceDiagnosisStateData");

        /// <summary>
        /// directControlActivityListData
        /// </summary>
        public static FunctionType  DirectControlActivityListData   { get; }
            = Register("directControlActivityListData");

        /// <summary>
        /// directControlDescriptionData
        /// </summary>
        public static FunctionType  DirectControlDescriptionData   { get; }
            = Register("directControlDescriptionData");

        /// <summary>
        /// electricalConnectionDescriptionListData
        /// </summary>
        public static FunctionType  ElectricalConnectionDescriptionListData   { get; }
            = Register("electricalConnectionDescriptionListData");

        /// <summary>
        /// electricalConnectionParameterDescriptionListData
        /// </summary>
        public static FunctionType  ElectricalConnectionParameterDescriptionListData   { get; }
            = Register("electricalConnectionParameterDescriptionListData");

        /// <summary>
        /// electricalConnectionStateListData
        /// </summary>
        public static FunctionType  ElectricalConnectionStateListData   { get; }
            = Register("electricalConnectionStateListData");

        /// <summary>
        /// hvacOperationModeDescriptionListData
        /// </summary>
        public static FunctionType  HvacOperationModeDescriptionListData   { get; }
            = Register("hvacOperationModeDescriptionListData");

        /// <summary>
        /// hvacOverrunDescriptionListData
        /// </summary>
        public static FunctionType  HvacOverrunDescriptionListData   { get; }
            = Register("hvacOverrunDescriptionListData");

        /// <summary>
        /// hvacOverrunListData
        /// </summary>
        public static FunctionType  HvacOverrunListData   { get; }
            = Register("hvacOverrunListData");

        /// <summary>
        /// hvacSystemFunctionDescriptionListData
        /// </summary>
        public static FunctionType  HvacSystemFunctionDescriptionListData   { get; }
            = Register("hvacSystemFunctionDescriptionListData");

        /// <summary>
        /// hvacSystemFunctionListData
        /// </summary>
        public static FunctionType  HvacSystemFunctionListData   { get; }
            = Register("hvacSystemFunctionListData");

        /// <summary>
        /// hvacSystemFunctionOperationModeRelationListData
        /// </summary>
        public static FunctionType  HvacSystemFunctionOperationModeRelationListData   { get; }
            = Register("hvacSystemFunctionOperationModeRelationListData");

        /// <summary>
        /// hvacSystemFunctionPowerSequenceRelationListData
        /// </summary>
        public static FunctionType  HvacSystemFunctionPowerSequenceRelationListData   { get; }
            = Register("hvacSystemFunctionPowerSequenceRelationListData");

        /// <summary>
        /// hvacSystemFunctionSetpointRelationListData
        /// </summary>
        public static FunctionType  HvacSystemFunctionSetpointRelationListData   { get; }
            = Register("hvacSystemFunctionSetpointRelationListData");

        /// <summary>
        /// loadControlEventListData
        /// </summary>
        public static FunctionType  LoadControlEventListData   { get; }
            = Register("loadControlEventListData");

        /// <summary>
        /// loadControlStateListData
        /// </summary>
        public static FunctionType  LoadControlStateListData   { get; }
            = Register("loadControlStateListData");

        /// <summary>
        /// measurementConstraintsListData
        /// </summary>
        public static FunctionType  MeasurementConstraintsListData   { get; }
            = Register("measurementConstraintsListData");

        /// <summary>
        /// measurementDescriptionListData
        /// </summary>
        public static FunctionType  MeasurementDescriptionListData   { get; }
            = Register("measurementDescriptionListData");

        /// <summary>
        /// measurementListData
        /// </summary>
        public static FunctionType  MeasurementListData   { get; }
            = Register("measurementListData");

        /// <summary>
        /// measurementThresholdRelationListData
        /// </summary>
        public static FunctionType  MeasurementThresholdRelationListData   { get; }
            = Register("measurementThresholdRelationListData");

        /// <summary>
        /// messagingListData
        /// </summary>
        public static FunctionType  MessagingListData   { get; }
            = Register("messagingListData");

        /// <summary>
        /// networkManagementAbortCall
        /// </summary>
        public static FunctionType  NetworkManagementAbortCall   { get; }
            = Register("networkManagementAbortCall");

        /// <summary>
        /// networkManagementAddNodeCall
        /// </summary>
        public static FunctionType  NetworkManagementAddNodeCall   { get; }
            = Register("networkManagementAddNodeCall");

        /// <summary>
        /// networkManagementDeviceDescriptionListData
        /// </summary>
        public static FunctionType  NetworkManagementDeviceDescriptionListData   { get; }
            = Register("networkManagementDeviceDescriptionListData");

        /// <summary>
        /// networkManagementDiscoverCall
        /// </summary>
        public static FunctionType  NetworkManagementDiscoverCall   { get; }
            = Register("networkManagementDiscoverCall");

        /// <summary>
        /// networkManagementEntityDescriptionListData
        /// </summary>
        public static FunctionType  NetworkManagementEntityDescriptionListData   { get; }
            = Register("networkManagementEntityDescriptionListData");

        /// <summary>
        /// networkManagementFeatureDescriptionListData
        /// </summary>
        public static FunctionType  NetworkManagementFeatureDescriptionListData   { get; }
            = Register("networkManagementFeatureDescriptionListData");

        /// <summary>
        /// networkManagementJoiningModeData
        /// </summary>
        public static FunctionType  NetworkManagementJoiningModeData   { get; }
            = Register("networkManagementJoiningModeData");

        /// <summary>
        /// networkManagementModifyNodeCall
        /// </summary>
        public static FunctionType  NetworkManagementModifyNodeCall   { get; }
            = Register("networkManagementModifyNodeCall");

        /// <summary>
        /// networkManagementProcessStateData
        /// </summary>
        public static FunctionType  NetworkManagementProcessStateData   { get; }
            = Register("networkManagementProcessStateData");

        /// <summary>
        /// networkManagementRemoveNodeCall
        /// </summary>
        public static FunctionType  NetworkManagementRemoveNodeCall   { get; }
            = Register("networkManagementRemoveNodeCall");

        /// <summary>
        /// networkManagementReportCandidateData
        /// </summary>
        public static FunctionType  NetworkManagementReportCandidateData   { get; }
            = Register("networkManagementReportCandidateData");

        /// <summary>
        /// networkManagementScanNetworkCall
        /// </summary>
        public static FunctionType  NetworkManagementScanNetworkCall   { get; }
            = Register("networkManagementScanNetworkCall");

        /// <summary>
        /// nodeManagementBindingData
        /// </summary>
        public static FunctionType  NodeManagementBindingData   { get; }
            = Register("nodeManagementBindingData");

        /// <summary>
        /// nodeManagementBindingDeleteCall
        /// </summary>
        public static FunctionType  NodeManagementBindingDeleteCall   { get; }
            = Register("nodeManagementBindingDeleteCall");

        /// <summary>
        /// nodeManagementBindingRequestCall
        /// </summary>
        public static FunctionType  NodeManagementBindingRequestCall   { get; }
            = Register("nodeManagementBindingRequestCall");

        /// <summary>
        /// nodeManagementDestinationListData
        /// </summary>
        public static FunctionType  NodeManagementDestinationListData   { get; }
            = Register("nodeManagementDestinationListData");

        /// <summary>
        /// nodeManagementDetailedDiscoveryData
        /// </summary>
        public static FunctionType  NodeManagementDetailedDiscoveryData   { get; }
            = Register("nodeManagementDetailedDiscoveryData");

        /// <summary>
        /// nodeManagementSubscriptionData
        /// </summary>
        public static FunctionType  NodeManagementSubscriptionData   { get; }
            = Register("nodeManagementSubscriptionData");

        /// <summary>
        /// nodeManagementSubscriptionDeleteCall
        /// </summary>
        public static FunctionType  NodeManagementSubscriptionDeleteCall   { get; }
            = Register("nodeManagementSubscriptionDeleteCall");

        /// <summary>
        /// nodeManagementSubscriptionRequestCall
        /// </summary>
        public static FunctionType  NodeManagementSubscriptionRequestCall   { get; }
            = Register("nodeManagementSubscriptionRequestCall");

        /// <summary>
        /// operatingConstraintsDurationListData
        /// </summary>
        public static FunctionType  OperatingConstraintsDurationListData   { get; }
            = Register("operatingConstraintsDurationListData");

        /// <summary>
        /// operatingConstraintsInterruptListData
        /// </summary>
        public static FunctionType  OperatingConstraintsInterruptListData   { get; }
            = Register("operatingConstraintsInterruptListData");

        /// <summary>
        /// operatingConstraintsPowerDescriptionListData
        /// </summary>
        public static FunctionType  OperatingConstraintsPowerDescriptionListData   { get; }
            = Register("operatingConstraintsPowerDescriptionListData");

        /// <summary>
        /// operatingConstraintsPowerLevelListData
        /// </summary>
        public static FunctionType  OperatingConstraintsPowerLevelListData   { get; }
            = Register("operatingConstraintsPowerLevelListData");

        /// <summary>
        /// operatingConstraintsPowerRangeListData
        /// </summary>
        public static FunctionType  OperatingConstraintsPowerRangeListData   { get; }
            = Register("operatingConstraintsPowerRangeListData");

        /// <summary>
        /// operatingConstraintsResumeImplicationListData
        /// </summary>
        public static FunctionType  OperatingConstraintsResumeImplicationListData   { get; }
            = Register("operatingConstraintsResumeImplicationListData");

        /// <summary>
        /// powerSequenceAlternativesRelationListData
        /// </summary>
        public static FunctionType  PowerSequenceAlternativesRelationListData   { get; }
            = Register("powerSequenceAlternativesRelationListData");

        /// <summary>
        /// powerSequenceDescriptionListData
        /// </summary>
        public static FunctionType  PowerSequenceDescriptionListData   { get; }
            = Register("powerSequenceDescriptionListData");

        /// <summary>
        /// powerSequenceNodeScheduleInformationData
        /// </summary>
        public static FunctionType  PowerSequenceNodeScheduleInformationData   { get; }
            = Register("powerSequenceNodeScheduleInformationData");

        /// <summary>
        /// powerSequencePriceCalculationRequestCall
        /// </summary>
        public static FunctionType  PowerSequencePriceCalculationRequestCall   { get; }
            = Register("powerSequencePriceCalculationRequestCall");

        /// <summary>
        /// powerSequencePriceListData
        /// </summary>
        public static FunctionType  PowerSequencePriceListData   { get; }
            = Register("powerSequencePriceListData");

        /// <summary>
        /// powerSequenceScheduleConfigurationRequestCall
        /// </summary>
        public static FunctionType  PowerSequenceScheduleConfigurationRequestCall   { get; }
            = Register("powerSequenceScheduleConfigurationRequestCall");

        /// <summary>
        /// powerSequenceScheduleConstraintsListData
        /// </summary>
        public static FunctionType  PowerSequenceScheduleConstraintsListData   { get; }
            = Register("powerSequenceScheduleConstraintsListData");

        /// <summary>
        /// powerSequenceScheduleListData
        /// </summary>
        public static FunctionType  PowerSequenceScheduleListData   { get; }
            = Register("powerSequenceScheduleListData");

        /// <summary>
        /// powerSequenceSchedulePreferenceListData
        /// </summary>
        public static FunctionType  PowerSequenceSchedulePreferenceListData   { get; }
            = Register("powerSequenceSchedulePreferenceListData");

        /// <summary>
        /// powerSequenceStateListData
        /// </summary>
        public static FunctionType  PowerSequenceStateListData   { get; }
            = Register("powerSequenceStateListData");

        /// <summary>
        /// powerTimeSlotScheduleConstraintsListData
        /// </summary>
        public static FunctionType  PowerTimeSlotScheduleConstraintsListData   { get; }
            = Register("powerTimeSlotScheduleConstraintsListData");

        /// <summary>
        /// powerTimeSlotScheduleListData
        /// </summary>
        public static FunctionType  PowerTimeSlotScheduleListData   { get; }
            = Register("powerTimeSlotScheduleListData");

        /// <summary>
        /// powerTimeSlotValueListData
        /// </summary>
        public static FunctionType  PowerTimeSlotValueListData   { get; }
            = Register("powerTimeSlotValueListData");

        /// <summary>
        /// resultData
        /// </summary>
        public static FunctionType  ResultData   { get; }
            = Register("resultData");

        /// <summary>
        /// sensingDescriptionData
        /// </summary>
        public static FunctionType  SensingDescriptionData   { get; }
            = Register("sensingDescriptionData");

        /// <summary>
        /// sensingListData
        /// </summary>
        public static FunctionType  SensingListData   { get; }
            = Register("sensingListData");

        /// <summary>
        /// sessionIdentificationListData
        /// </summary>
        public static FunctionType  SessionIdentificationListData   { get; }
            = Register("sessionIdentificationListData");

        /// <summary>
        /// sessionMeasurementRelationListData
        /// </summary>
        public static FunctionType  SessionMeasurementRelationListData   { get; }
            = Register("sessionMeasurementRelationListData");

        /// <summary>
        /// setpointConstraintsListData
        /// </summary>
        public static FunctionType  SetpointConstraintsListData   { get; }
            = Register("setpointConstraintsListData");

        /// <summary>
        /// setpointDescriptionListData
        /// </summary>
        public static FunctionType  SetpointDescriptionListData   { get; }
            = Register("setpointDescriptionListData");

        /// <summary>
        /// setpointListData
        /// </summary>
        public static FunctionType  SetpointListData   { get; }
            = Register("setpointListData");

        /// <summary>
        /// smartEnergyManagementPsConfigurationRequestCall
        /// </summary>
        public static FunctionType  SmartEnergyManagementPsConfigurationRequestCall   { get; }
            = Register("smartEnergyManagementPsConfigurationRequestCall");

        /// <summary>
        /// smartEnergyManagementPsData
        /// </summary>
        public static FunctionType  SmartEnergyManagementPsData   { get; }
            = Register("smartEnergyManagementPsData");

        /// <summary>
        /// smartEnergyManagementPsPriceCalculationRequestCall
        /// </summary>
        public static FunctionType  SmartEnergyManagementPsPriceCalculationRequestCall   { get; }
            = Register("smartEnergyManagementPsPriceCalculationRequestCall");

        /// <summary>
        /// smartEnergyManagementPsPriceData
        /// </summary>
        public static FunctionType  SmartEnergyManagementPsPriceData   { get; }
            = Register("smartEnergyManagementPsPriceData");

        /// <summary>
        /// specificationVersionListData
        /// </summary>
        public static FunctionType  SpecificationVersionListData   { get; }
            = Register("specificationVersionListData");

        /// <summary>
        /// subscriptionManagementDeleteCall
        /// </summary>
        public static FunctionType  SubscriptionManagementDeleteCall   { get; }
            = Register("subscriptionManagementDeleteCall");

        /// <summary>
        /// subscriptionManagementEntryListData
        /// </summary>
        public static FunctionType  SubscriptionManagementEntryListData   { get; }
            = Register("subscriptionManagementEntryListData");

        /// <summary>
        /// subscriptionManagementRequestCall
        /// </summary>
        public static FunctionType  SubscriptionManagementRequestCall   { get; }
            = Register("subscriptionManagementRequestCall");

        /// <summary>
        /// supplyConditionDescriptionListData
        /// </summary>
        public static FunctionType  SupplyConditionDescriptionListData   { get; }
            = Register("supplyConditionDescriptionListData");

        /// <summary>
        /// supplyConditionListData
        /// </summary>
        public static FunctionType  SupplyConditionListData   { get; }
            = Register("supplyConditionListData");

        /// <summary>
        /// supplyConditionThresholdRelationListData
        /// </summary>
        public static FunctionType  SupplyConditionThresholdRelationListData   { get; }
            = Register("supplyConditionThresholdRelationListData");

        /// <summary>
        /// taskManagementJobDescriptionListData
        /// </summary>
        public static FunctionType  TaskManagementJobDescriptionListData   { get; }
            = Register("taskManagementJobDescriptionListData");

        /// <summary>
        /// taskManagementJobListData
        /// </summary>
        public static FunctionType  TaskManagementJobListData   { get; }
            = Register("taskManagementJobListData");

        /// <summary>
        /// taskManagementJobRelationListData
        /// </summary>
        public static FunctionType  TaskManagementJobRelationListData   { get; }
            = Register("taskManagementJobRelationListData");

        /// <summary>
        /// taskManagementOverviewData
        /// </summary>
        public static FunctionType  TaskManagementOverviewData   { get; }
            = Register("taskManagementOverviewData");

        /// <summary>
        /// thresholdConstraintsListData
        /// </summary>
        public static FunctionType  ThresholdConstraintsListData   { get; }
            = Register("thresholdConstraintsListData");

        /// <summary>
        /// thresholdDescriptionListData
        /// </summary>
        public static FunctionType  ThresholdDescriptionListData   { get; }
            = Register("thresholdDescriptionListData");

        /// <summary>
        /// thresholdListData
        /// </summary>
        public static FunctionType  ThresholdListData   { get; }
            = Register("thresholdListData");

        /// <summary>
        /// timeDistributorData
        /// </summary>
        public static FunctionType  TimeDistributorData   { get; }
            = Register("timeDistributorData");

        /// <summary>
        /// timeDistributorEnquiryCall
        /// </summary>
        public static FunctionType  TimeDistributorEnquiryCall   { get; }
            = Register("timeDistributorEnquiryCall");

        /// <summary>
        /// timeInformationData
        /// </summary>
        public static FunctionType  TimeInformationData   { get; }
            = Register("timeInformationData");

        /// <summary>
        /// timePrecisionData
        /// </summary>
        public static FunctionType  TimePrecisionData   { get; }
            = Register("timePrecisionData");

        /// <summary>
        /// timeTableConstraintsListData
        /// </summary>
        public static FunctionType  TimeTableConstraintsListData   { get; }
            = Register("timeTableConstraintsListData");

        /// <summary>
        /// timeTableDescriptionListData
        /// </summary>
        public static FunctionType  TimeTableDescriptionListData   { get; }
            = Register("timeTableDescriptionListData");

        /// <summary>
        /// timeTableListData
        /// </summary>
        public static FunctionType  TimeTableListData   { get; }
            = Register("timeTableListData");

        /// <summary>
        /// deviceConfigurationKeyValueConstraintsListData
        /// </summary>
        public static FunctionType  DeviceConfigurationKeyValueConstraintsListData   { get; }
            = Register("deviceConfigurationKeyValueConstraintsListData");

        /// <summary>
        /// deviceConfigurationKeyValueListData
        /// </summary>
        public static FunctionType  DeviceConfigurationKeyValueListData   { get; }
            = Register("deviceConfigurationKeyValueListData");

        /// <summary>
        /// deviceConfigurationKeyValueDescriptionListData
        /// </summary>
        public static FunctionType  DeviceConfigurationKeyValueDescriptionListData   { get; }
            = Register("deviceConfigurationKeyValueDescriptionListData");

        /// <summary>
        /// loadControlLimitConstraintsListData
        /// </summary>
        public static FunctionType  LoadControlLimitConstraintsListData   { get; }
            = Register("loadControlLimitConstraintsListData");

        /// <summary>
        /// loadControlLimitDescriptionListData
        /// </summary>
        public static FunctionType  LoadControlLimitDescriptionListData   { get; }
            = Register("loadControlLimitDescriptionListData");

        /// <summary>
        /// loadControlLimitListData
        /// </summary>
        public static FunctionType  LoadControlLimitListData   { get; }
            = Register("loadControlLimitListData");

        /// <summary>
        /// loadControlNodeData
        /// </summary>
        public static FunctionType  LoadControlNodeData   { get; }
            = Register("loadControlNodeData");

        /// <summary>
        /// timeSeriesConstraintsListData
        /// </summary>
        public static FunctionType  TimeSeriesConstraintsListData   { get; }
            = Register("timeSeriesConstraintsListData");

        /// <summary>
        /// timeSeriesDescriptionListData
        /// </summary>
        public static FunctionType  TimeSeriesDescriptionListData   { get; }
            = Register("timeSeriesDescriptionListData");

        /// <summary>
        /// timeSeriesListData
        /// </summary>
        public static FunctionType  TimeSeriesListData   { get; }
            = Register("timeSeriesListData");

        /// <summary>
        /// tariffOverallConstraintsData
        /// </summary>
        public static FunctionType  TariffOverallConstraintsData   { get; }
            = Register("tariffOverallConstraintsData");

        /// <summary>
        /// tariffListData
        /// </summary>
        public static FunctionType  TariffListData   { get; }
            = Register("tariffListData");

        /// <summary>
        /// tariffBoundaryRelationListData
        /// </summary>
        public static FunctionType  TariffBoundaryRelationListData   { get; }
            = Register("tariffBoundaryRelationListData");

        /// <summary>
        /// tariffTierRelationListData
        /// </summary>
        public static FunctionType  TariffTierRelationListData   { get; }
            = Register("tariffTierRelationListData");

        /// <summary>
        /// tariffDescriptionListData
        /// </summary>
        public static FunctionType  TariffDescriptionListData   { get; }
            = Register("tariffDescriptionListData");

        /// <summary>
        /// tierBoundaryListData
        /// </summary>
        public static FunctionType  TierBoundaryListData   { get; }
            = Register("tierBoundaryListData");

        /// <summary>
        /// tierBoundaryDescriptionListData
        /// </summary>
        public static FunctionType  TierBoundaryDescriptionListData   { get; }
            = Register("tierBoundaryDescriptionListData");

        /// <summary>
        /// commodityListData
        /// </summary>
        public static FunctionType  CommodityListData   { get; }
            = Register("commodityListData");

        /// <summary>
        /// tierListData
        /// </summary>
        public static FunctionType  TierListData   { get; }
            = Register("tierListData");

        /// <summary>
        /// tierIncentiveRelationListData
        /// </summary>
        public static FunctionType  TierIncentiveRelationListData   { get; }
            = Register("tierIncentiveRelationListData");

        /// <summary>
        /// tierDescriptionListData
        /// </summary>
        public static FunctionType  TierDescriptionListData   { get; }
            = Register("tierDescriptionListData");

        /// <summary>
        /// incentiveListData
        /// </summary>
        public static FunctionType  IncentiveListData   { get; }
            = Register("incentiveListData");

        /// <summary>
        /// incentiveDescriptionListData
        /// </summary>
        public static FunctionType  IncentiveDescriptionListData   { get; }
            = Register("incentiveDescriptionListData");

        /// <summary>
        /// incentiveTableData
        /// </summary>
        public static FunctionType  IncentiveTableData   { get; }
            = Register("incentiveTableData");

        /// <summary>
        /// incentiveTableDescriptionData
        /// </summary>
        public static FunctionType  IncentiveTableDescriptionData   { get; }
            = Register("incentiveTableDescriptionData");

        /// <summary>
        /// incentiveTableConstraintsData
        /// </summary>
        public static FunctionType  IncentiveTableConstraintsData   { get; }
            = Register("incentiveTableConstraintsData");

        /// <summary>
        /// electricalConnectionPermittedValueSetListData
        /// </summary>
        public static FunctionType  ElectricalConnectionPermittedValueSetListData   { get; }
            = Register("electricalConnectionPermittedValueSetListData");

        /// <summary>
        /// useCaseInformationListData
        /// </summary>
        public static FunctionType  UseCaseInformationListData   { get; }
            = Register("useCaseInformationListData");

        /// <summary>
        /// nodeManagementUseCaseData
        /// </summary>
        public static FunctionType  NodeManagementUseCaseData   { get; }
            = Register("nodeManagementUseCaseData");

        /// <summary>
        /// billConstraintsListData
        /// </summary>
        public static FunctionType  BillConstraintsListData   { get; }
            = Register("billConstraintsListData");

        /// <summary>
        /// billDescriptionListData
        /// </summary>
        public static FunctionType  BillDescriptionListData   { get; }
            = Register("billDescriptionListData");

        /// <summary>
        /// billListData
        /// </summary>
        public static FunctionType  BillListData   { get; }
            = Register("billListData");

        /// <summary>
        /// identificationListData
        /// </summary>
        public static FunctionType  IdentificationListData   { get; }
            = Register("identificationListData");

        /// <summary>
        /// measurementSeriesListData
        /// </summary>
        public static FunctionType  MeasurementSeriesListData   { get; }
            = Register("measurementSeriesListData");

        /// <summary>
        /// electricalConnectionCharacteristicListData
        /// </summary>
        public static FunctionType  ElectricalConnectionCharacteristicListData   { get; }
            = Register("electricalConnectionCharacteristicListData");

        /// <summary>
        /// stateInformationListData
        /// </summary>
        public static FunctionType  StateInformationListData   { get; }
            = Register("stateInformationListData");

        #endregion

        #region Validity

        /// <summary>
        /// All values defined by SPINE 1.3.0.
        /// </summary>
        public static IEnumerable<FunctionType>  All    { get; }
            = [
                  ActuatorLevelData,
                  ActuatorLevelDescriptionData,
                  ActuatorSwitchData,
                  ActuatorSwitchDescriptionData,
                  AlarmListData,
                  BindingManagementDeleteCall,
                  BindingManagementEntryListData,
                  BindingManagementRequestCall,
                  DataTunnelingCall,
                  DeviceClassificationManufacturerData,
                  DeviceClassificationUserData,
                  DeviceDiagnosisHeartbeatData,
                  DeviceDiagnosisServiceData,
                  DeviceDiagnosisStateData,
                  DirectControlActivityListData,
                  DirectControlDescriptionData,
                  ElectricalConnectionDescriptionListData,
                  ElectricalConnectionParameterDescriptionListData,
                  ElectricalConnectionStateListData,
                  HvacOperationModeDescriptionListData,
                  HvacOverrunDescriptionListData,
                  HvacOverrunListData,
                  HvacSystemFunctionDescriptionListData,
                  HvacSystemFunctionListData,
                  HvacSystemFunctionOperationModeRelationListData,
                  HvacSystemFunctionPowerSequenceRelationListData,
                  HvacSystemFunctionSetpointRelationListData,
                  LoadControlEventListData,
                  LoadControlStateListData,
                  MeasurementConstraintsListData,
                  MeasurementDescriptionListData,
                  MeasurementListData,
                  MeasurementThresholdRelationListData,
                  MessagingListData,
                  NetworkManagementAbortCall,
                  NetworkManagementAddNodeCall,
                  NetworkManagementDeviceDescriptionListData,
                  NetworkManagementDiscoverCall,
                  NetworkManagementEntityDescriptionListData,
                  NetworkManagementFeatureDescriptionListData,
                  NetworkManagementJoiningModeData,
                  NetworkManagementModifyNodeCall,
                  NetworkManagementProcessStateData,
                  NetworkManagementRemoveNodeCall,
                  NetworkManagementReportCandidateData,
                  NetworkManagementScanNetworkCall,
                  NodeManagementBindingData,
                  NodeManagementBindingDeleteCall,
                  NodeManagementBindingRequestCall,
                  NodeManagementDestinationListData,
                  NodeManagementDetailedDiscoveryData,
                  NodeManagementSubscriptionData,
                  NodeManagementSubscriptionDeleteCall,
                  NodeManagementSubscriptionRequestCall,
                  OperatingConstraintsDurationListData,
                  OperatingConstraintsInterruptListData,
                  OperatingConstraintsPowerDescriptionListData,
                  OperatingConstraintsPowerLevelListData,
                  OperatingConstraintsPowerRangeListData,
                  OperatingConstraintsResumeImplicationListData,
                  PowerSequenceAlternativesRelationListData,
                  PowerSequenceDescriptionListData,
                  PowerSequenceNodeScheduleInformationData,
                  PowerSequencePriceCalculationRequestCall,
                  PowerSequencePriceListData,
                  PowerSequenceScheduleConfigurationRequestCall,
                  PowerSequenceScheduleConstraintsListData,
                  PowerSequenceScheduleListData,
                  PowerSequenceSchedulePreferenceListData,
                  PowerSequenceStateListData,
                  PowerTimeSlotScheduleConstraintsListData,
                  PowerTimeSlotScheduleListData,
                  PowerTimeSlotValueListData,
                  ResultData,
                  SensingDescriptionData,
                  SensingListData,
                  SessionIdentificationListData,
                  SessionMeasurementRelationListData,
                  SetpointConstraintsListData,
                  SetpointDescriptionListData,
                  SetpointListData,
                  SmartEnergyManagementPsConfigurationRequestCall,
                  SmartEnergyManagementPsData,
                  SmartEnergyManagementPsPriceCalculationRequestCall,
                  SmartEnergyManagementPsPriceData,
                  SpecificationVersionListData,
                  SubscriptionManagementDeleteCall,
                  SubscriptionManagementEntryListData,
                  SubscriptionManagementRequestCall,
                  SupplyConditionDescriptionListData,
                  SupplyConditionListData,
                  SupplyConditionThresholdRelationListData,
                  TaskManagementJobDescriptionListData,
                  TaskManagementJobListData,
                  TaskManagementJobRelationListData,
                  TaskManagementOverviewData,
                  ThresholdConstraintsListData,
                  ThresholdDescriptionListData,
                  ThresholdListData,
                  TimeDistributorData,
                  TimeDistributorEnquiryCall,
                  TimeInformationData,
                  TimePrecisionData,
                  TimeTableConstraintsListData,
                  TimeTableDescriptionListData,
                  TimeTableListData,
                  DeviceConfigurationKeyValueConstraintsListData,
                  DeviceConfigurationKeyValueListData,
                  DeviceConfigurationKeyValueDescriptionListData,
                  LoadControlLimitConstraintsListData,
                  LoadControlLimitDescriptionListData,
                  LoadControlLimitListData,
                  LoadControlNodeData,
                  TimeSeriesConstraintsListData,
                  TimeSeriesDescriptionListData,
                  TimeSeriesListData,
                  TariffOverallConstraintsData,
                  TariffListData,
                  TariffBoundaryRelationListData,
                  TariffTierRelationListData,
                  TariffDescriptionListData,
                  TierBoundaryListData,
                  TierBoundaryDescriptionListData,
                  CommodityListData,
                  TierListData,
                  TierIncentiveRelationListData,
                  TierDescriptionListData,
                  IncentiveListData,
                  IncentiveDescriptionListData,
                  IncentiveTableData,
                  IncentiveTableDescriptionData,
                  IncentiveTableConstraintsData,
                  ElectricalConnectionPermittedValueSetListData,
                  UseCaseInformationListData,
                  NodeManagementUseCaseData,
                  BillConstraintsListData,
                  BillDescriptionListData,
                  BillListData,
                  IdentificationListData,
                  MeasurementSeriesListData,
                  ElectricalConnectionCharacteristicListData,
                  StateInformationListData
              ];

        /// <summary>
        /// Whether this is one of the values defined by SPINE 1.3.0.
        /// </summary>
        public Boolean IsDefined
            => All.Contains(this);

        /// <summary>
        /// Whether this enumeration may carry values which the specification does not define.
        /// </summary>
        public static Boolean IsExtensible    { get; }
            = true;

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator == (FunctionType Value1, FunctionType Value2)
            => Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator != (FunctionType Value1, FunctionType Value2)
            => !Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator < (FunctionType Value1, FunctionType Value2)
            => Value1.CompareTo(Value2) <  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator <= (FunctionType Value1, FunctionType Value2)
            => Value1.CompareTo(Value2) <= 0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator > (FunctionType Value1, FunctionType Value2)
            => Value1.CompareTo(Value2) >  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator >= (FunctionType Value1, FunctionType Value2)
            => Value1.CompareTo(Value2) >= 0;

        #endregion

        #region IComparable<FunctionType> Members

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public Int32 CompareTo(Object? Object)

            => Object is FunctionType value
                   ? CompareTo(value)
                   : throw new ArgumentException("The given object is not a FunctionType!",
                                                 nameof(Object));

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Int32 CompareTo(FunctionType Value)

            => String.Compare(InternalId,
                              Value.InternalId,
                              StringComparison.Ordinal);

        #endregion

        #region IEquatable<FunctionType> Members

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public override Boolean Equals(Object? Object)

            => Object is FunctionType value &&
                   Equals(value);

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Boolean Equals(FunctionType Value)

            => String.Equals(InternalId,
                             Value.InternalId,
                             StringComparison.Ordinal);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()

            => InternalId?.GetHashCode() ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return the text representation of this value.
        /// </summary>
        public override String ToString()

            => InternalId ?? "";

        #endregion

    }

}
