/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     RoleType, from EEBus_SPINE_TS_CommonDataTypes.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;
using org.GraphDefined.Vanaheimr.Illias;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// Extension methods for RoleType.
    /// </summary>
    public static class RoleTypeExtensions
    {

        /// <summary>
        /// Indicates whether this RoleType is null or empty.
        /// </summary>
        /// <param name="Value">A RoleType.</param>
        public static Boolean IsNullOrEmpty(this RoleType? Value)
            => !Value.HasValue || Value.Value.IsNullOrEmpty;

        /// <summary>
        /// Indicates whether this RoleType is NOT null or empty.
        /// </summary>
        /// <param name="Value">A RoleType.</param>
        public static Boolean IsNotNullOrEmpty(this RoleType? Value)
            => Value.HasValue && Value.Value.IsNotNullOrEmpty;

    }


    /// <summary>
    /// RoleType (SPINE 1.3.0, EEBus_SPINE_TS_CommonDataTypes.xsd).
    ///
    /// The specification defines 3 value(s).
    /// It is not an extensible enumeration.
    ///
    /// Parsing is tolerant either way: a value which the specification does not
    /// define has to survive being received, so that it can be reported. Whether
    /// it is allowed here is decided by the conformance tests, see IsDefined.
    /// </summary>
    [JsonConverter(typeof(SPINEStringTypeConverter<RoleType>))]
    public readonly struct RoleType : IId,
                                    ISPINEStringType<RoleType>,
                                    IEquatable<RoleType>,
                                    IComparable<RoleType>
    {

        #region Data

        // Ordinal, not OrdinalIgnoreCase: the values of SPINE are case sensitive.
        // The units of measurement contain both "s" (second) and "S" (siemens).
        private readonly static Dictionary<String, RoleType>  lookup = new (StringComparer.Ordinal);
        private readonly        String                      InternalId;

        #endregion

        #region Properties

        /// <summary>
        /// Indicates whether this value is null or empty.
        /// </summary>
        public readonly  Boolean  IsNullOrEmpty
            => InternalId.IsNullOrEmpty();

        /// <summary>
        /// Indicates whether this value is NOT null or empty.
        /// </summary>
        public readonly  Boolean  IsNotNullOrEmpty
            => InternalId.IsNotNullOrEmpty();

        /// <summary>
        /// The length of the value.
        /// </summary>
        public readonly  UInt64   Length
            => (UInt64) (InternalId?.Length ?? 0);

        #endregion

        #region Constructor(s)

        private RoleType(String Text)
        {
            this.InternalId = Text;
        }

        #endregion


        #region (private static) Register(Text)

        private static RoleType Register(String Text)

            => lookup.AddAndReturnValue(
                   Text,
                   new RoleType(Text)
               );

        #endregion


        #region (static) Parse   (Text)

        /// <summary>
        /// Parse the given text as a RoleType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static RoleType Parse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            throw new ArgumentException("The given text representation of a RoleType is invalid!",
                                        nameof(Text));

        }

        #endregion

        #region (static) TryParse(Text)

        /// <summary>
        /// Try to parse the given text as a RoleType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static RoleType? TryParse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            return null;

        }

        #endregion

        #region (static) TryParse(Text, out Value)

        /// <summary>
        /// Try to parse the given text as a RoleType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        /// <param name="Value">The parsed value.</param>
        public static Boolean TryParse(String Text, out RoleType Value)
        {

            Text = Text.Trim();

            if (Text.IsNotNullOrEmpty())
            {

                if (!lookup.TryGetValue(Text, out Value))
                    Value = Register(Text);

                return true;

            }

            Value = default;
            return false;

        }

        #endregion


        #region Static definitions

        /// <summary>
        /// client
        /// </summary>
        public static RoleType  Client   { get; }
            = Register("client");

        /// <summary>
        /// server
        /// </summary>
        public static RoleType  Server   { get; }
            = Register("server");

        /// <summary>
        /// special
        /// </summary>
        public static RoleType  Special   { get; }
            = Register("special");

        #endregion

        #region Validity

        /// <summary>
        /// All values defined by SPINE 1.3.0.
        /// </summary>
        public static IEnumerable<RoleType>  All    { get; }
            = [
                  Client,
                  Server,
                  Special
              ];

        /// <summary>
        /// Whether this is one of the values defined by SPINE 1.3.0.
        /// </summary>
        public Boolean IsDefined
            => All.Contains(this);

        /// <summary>
        /// Whether this enumeration may carry values which the specification does not define.
        /// </summary>
        public static Boolean IsExtensible    { get; }
            = false;

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator == (RoleType Value1, RoleType Value2)
            => Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator != (RoleType Value1, RoleType Value2)
            => !Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator < (RoleType Value1, RoleType Value2)
            => Value1.CompareTo(Value2) <  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator <= (RoleType Value1, RoleType Value2)
            => Value1.CompareTo(Value2) <= 0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator > (RoleType Value1, RoleType Value2)
            => Value1.CompareTo(Value2) >  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator >= (RoleType Value1, RoleType Value2)
            => Value1.CompareTo(Value2) >= 0;

        #endregion

        #region IComparable<RoleType> Members

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public Int32 CompareTo(Object? Object)

            => Object is RoleType value
                   ? CompareTo(value)
                   : throw new ArgumentException("The given object is not a RoleType!",
                                                 nameof(Object));

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Int32 CompareTo(RoleType Value)

            => String.Compare(InternalId,
                              Value.InternalId,
                              StringComparison.Ordinal);

        #endregion

        #region IEquatable<RoleType> Members

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public override Boolean Equals(Object? Object)

            => Object is RoleType value &&
                   Equals(value);

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Boolean Equals(RoleType Value)

            => String.Equals(InternalId,
                             Value.InternalId,
                             StringComparison.Ordinal);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()

            => InternalId?.GetHashCode() ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return the text representation of this value.
        /// </summary>
        public override String ToString()

            => InternalId ?? "";

        #endregion

    }

}
