/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated>
//     SensingStateType, from EEBus_SPINE_TS_Sensing.xsd.
//
//     Generated from the official SPINE 1.3.0 XSDs by Apps/EEBUSModelGen.
//     Every change made here is lost the next time the generator runs.
//
//     Where the XSD cannot express what is needed - the ISO 8601 types, the
//     identifiers of a data type - the answer belongs into the generator or
//     into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/.
// </auto-generated>

#region Usings

using Newtonsoft.Json;
using org.GraphDefined.Vanaheimr.Illias;

#endregion

#nullable enable

namespace cloud.charging.open.protocols.EEBUS.SPINE.Model
{

    /// <summary>
    /// Extension methods for SensingStateType.
    /// </summary>
    public static class SensingStateTypeExtensions
    {

        /// <summary>
        /// Indicates whether this SensingStateType is null or empty.
        /// </summary>
        /// <param name="Value">A SensingStateType.</param>
        public static Boolean IsNullOrEmpty(this SensingStateType? Value)
            => !Value.HasValue || Value.Value.IsNullOrEmpty;

        /// <summary>
        /// Indicates whether this SensingStateType is NOT null or empty.
        /// </summary>
        /// <param name="Value">A SensingStateType.</param>
        public static Boolean IsNotNullOrEmpty(this SensingStateType? Value)
            => Value.HasValue && Value.Value.IsNotNullOrEmpty;

    }


    /// <summary>
    /// SensingStateType (SPINE 1.3.0, EEBus_SPINE_TS_Sensing.xsd).
    ///
    /// The specification defines 36 value(s) and unions them with "EnumExtendType",
    /// so a value of a manufacturer is a legal value here.
    ///
    /// Parsing is tolerant either way: a value which the specification does not
    /// define has to survive being received, so that it can be reported. Whether
    /// it is allowed here is decided by the conformance tests, see IsDefined.
    /// </summary>
    [JsonConverter(typeof(SPINEStringTypeConverter<SensingStateType>))]
    public readonly struct SensingStateType : IId,
                                    ISPINEStringType<SensingStateType>,
                                    IEquatable<SensingStateType>,
                                    IComparable<SensingStateType>
    {

        #region Data

        // Ordinal, not OrdinalIgnoreCase: the values of SPINE are case sensitive.
        // The units of measurement contain both "s" (second) and "S" (siemens).
        private readonly static Dictionary<String, SensingStateType>  lookup = new (StringComparer.Ordinal);
        private readonly        String                      InternalId;

        #endregion

        #region Properties

        /// <summary>
        /// Indicates whether this value is null or empty.
        /// </summary>
        public readonly  Boolean  IsNullOrEmpty
            => InternalId.IsNullOrEmpty();

        /// <summary>
        /// Indicates whether this value is NOT null or empty.
        /// </summary>
        public readonly  Boolean  IsNotNullOrEmpty
            => InternalId.IsNotNullOrEmpty();

        /// <summary>
        /// The length of the value.
        /// </summary>
        public readonly  UInt64   Length
            => (UInt64) (InternalId?.Length ?? 0);

        #endregion

        #region Constructor(s)

        private SensingStateType(String Text)
        {
            this.InternalId = Text;
        }

        #endregion


        #region (private static) Register(Text)

        private static SensingStateType Register(String Text)

            => lookup.AddAndReturnValue(
                   Text,
                   new SensingStateType(Text)
               );

        #endregion


        #region (static) Parse   (Text)

        /// <summary>
        /// Parse the given text as a SensingStateType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static SensingStateType Parse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            throw new ArgumentException("The given text representation of a SensingStateType is invalid!",
                                        nameof(Text));

        }

        #endregion

        #region (static) TryParse(Text)

        /// <summary>
        /// Try to parse the given text as a SensingStateType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        public static SensingStateType? TryParse(String Text)
        {

            if (TryParse(Text, out var value))
                return value;

            return null;

        }

        #endregion

        #region (static) TryParse(Text, out Value)

        /// <summary>
        /// Try to parse the given text as a SensingStateType.
        /// </summary>
        /// <param name="Text">A text representation.</param>
        /// <param name="Value">The parsed value.</param>
        public static Boolean TryParse(String Text, out SensingStateType Value)
        {

            Text = Text.Trim();

            if (Text.IsNotNullOrEmpty())
            {

                if (!lookup.TryGetValue(Text, out Value))
                    Value = Register(Text);

                return true;

            }

            Value = default;
            return false;

        }

        #endregion


        #region Static definitions

        /// <summary>
        /// on
        /// </summary>
        public static SensingStateType  On   { get; }
            = Register("on");

        /// <summary>
        /// off
        /// </summary>
        public static SensingStateType  Off   { get; }
            = Register("off");

        /// <summary>
        /// toggle
        /// </summary>
        public static SensingStateType  Toggle   { get; }
            = Register("toggle");

        /// <summary>
        /// level
        /// </summary>
        public static SensingStateType  Level   { get; }
            = Register("level");

        /// <summary>
        /// levelUp
        /// </summary>
        public static SensingStateType  LevelUp   { get; }
            = Register("levelUp");

        /// <summary>
        /// levelDown
        /// </summary>
        public static SensingStateType  LevelDown   { get; }
            = Register("levelDown");

        /// <summary>
        /// levelStart
        /// </summary>
        public static SensingStateType  LevelStart   { get; }
            = Register("levelStart");

        /// <summary>
        /// levelStop
        /// </summary>
        public static SensingStateType  LevelStop   { get; }
            = Register("levelStop");

        /// <summary>
        /// levelAbsolute
        /// </summary>
        public static SensingStateType  LevelAbsolute   { get; }
            = Register("levelAbsolute");

        /// <summary>
        /// levelRelative
        /// </summary>
        public static SensingStateType  LevelRelative   { get; }
            = Register("levelRelative");

        /// <summary>
        /// levelPercentageAbsolute
        /// </summary>
        public static SensingStateType  LevelPercentageAbsolute   { get; }
            = Register("levelPercentageAbsolute");

        /// <summary>
        /// levelPercentageRelative
        /// </summary>
        public static SensingStateType  LevelPercentageRelative   { get; }
            = Register("levelPercentageRelative");

        /// <summary>
        /// pressed
        /// </summary>
        public static SensingStateType  Pressed   { get; }
            = Register("pressed");

        /// <summary>
        /// longPressed
        /// </summary>
        public static SensingStateType  LongPressed   { get; }
            = Register("longPressed");

        /// <summary>
        /// released
        /// </summary>
        public static SensingStateType  Released   { get; }
            = Register("released");

        /// <summary>
        /// changed
        /// </summary>
        public static SensingStateType  Changed   { get; }
            = Register("changed");

        /// <summary>
        /// started
        /// </summary>
        public static SensingStateType  Started   { get; }
            = Register("started");

        /// <summary>
        /// stopped
        /// </summary>
        public static SensingStateType  Stopped   { get; }
            = Register("stopped");

        /// <summary>
        /// paused
        /// </summary>
        public static SensingStateType  Paused   { get; }
            = Register("paused");

        /// <summary>
        /// middle
        /// </summary>
        public static SensingStateType  Middle   { get; }
            = Register("middle");

        /// <summary>
        /// up
        /// </summary>
        public static SensingStateType  Up   { get; }
            = Register("up");

        /// <summary>
        /// down
        /// </summary>
        public static SensingStateType  Down   { get; }
            = Register("down");

        /// <summary>
        /// forward
        /// </summary>
        public static SensingStateType  Forward   { get; }
            = Register("forward");

        /// <summary>
        /// backwards
        /// </summary>
        public static SensingStateType  Backwards   { get; }
            = Register("backwards");

        /// <summary>
        /// open
        /// </summary>
        public static SensingStateType  Open   { get; }
            = Register("open");

        /// <summary>
        /// closed
        /// </summary>
        public static SensingStateType  Closed   { get; }
            = Register("closed");

        /// <summary>
        /// opening
        /// </summary>
        public static SensingStateType  Opening   { get; }
            = Register("opening");

        /// <summary>
        /// closing
        /// </summary>
        public static SensingStateType  Closing   { get; }
            = Register("closing");

        /// <summary>
        /// high
        /// </summary>
        public static SensingStateType  High   { get; }
            = Register("high");

        /// <summary>
        /// low
        /// </summary>
        public static SensingStateType  Low   { get; }
            = Register("low");

        /// <summary>
        /// day
        /// </summary>
        public static SensingStateType  Day   { get; }
            = Register("day");

        /// <summary>
        /// night
        /// </summary>
        public static SensingStateType  Night   { get; }
            = Register("night");

        /// <summary>
        /// detected
        /// </summary>
        public static SensingStateType  Detected   { get; }
            = Register("detected");

        /// <summary>
        /// notDetected
        /// </summary>
        public static SensingStateType  NotDetected   { get; }
            = Register("notDetected");

        /// <summary>
        /// alarmed
        /// </summary>
        public static SensingStateType  Alarmed   { get; }
            = Register("alarmed");

        /// <summary>
        /// notAlarmed
        /// </summary>
        public static SensingStateType  NotAlarmed   { get; }
            = Register("notAlarmed");

        #endregion

        #region Validity

        /// <summary>
        /// All values defined by SPINE 1.3.0.
        /// </summary>
        public static IEnumerable<SensingStateType>  All    { get; }
            = [
                  On,
                  Off,
                  Toggle,
                  Level,
                  LevelUp,
                  LevelDown,
                  LevelStart,
                  LevelStop,
                  LevelAbsolute,
                  LevelRelative,
                  LevelPercentageAbsolute,
                  LevelPercentageRelative,
                  Pressed,
                  LongPressed,
                  Released,
                  Changed,
                  Started,
                  Stopped,
                  Paused,
                  Middle,
                  Up,
                  Down,
                  Forward,
                  Backwards,
                  Open,
                  Closed,
                  Opening,
                  Closing,
                  High,
                  Low,
                  Day,
                  Night,
                  Detected,
                  NotDetected,
                  Alarmed,
                  NotAlarmed
              ];

        /// <summary>
        /// Whether this is one of the values defined by SPINE 1.3.0.
        /// </summary>
        public Boolean IsDefined
            => All.Contains(this);

        /// <summary>
        /// Whether this enumeration may carry values which the specification does not define.
        /// </summary>
        public static Boolean IsExtensible    { get; }
            = true;

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator == (SensingStateType Value1, SensingStateType Value2)
            => Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator != (SensingStateType Value1, SensingStateType Value2)
            => !Value1.Equals(Value2);

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator < (SensingStateType Value1, SensingStateType Value2)
            => Value1.CompareTo(Value2) <  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator <= (SensingStateType Value1, SensingStateType Value2)
            => Value1.CompareTo(Value2) <= 0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator > (SensingStateType Value1, SensingStateType Value2)
            => Value1.CompareTo(Value2) >  0;

        /// <summary>
        /// Compares two values.
        /// </summary>
        public static Boolean operator >= (SensingStateType Value1, SensingStateType Value2)
            => Value1.CompareTo(Value2) >= 0;

        #endregion

        #region IComparable<SensingStateType> Members

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public Int32 CompareTo(Object? Object)

            => Object is SensingStateType value
                   ? CompareTo(value)
                   : throw new ArgumentException("The given object is not a SensingStateType!",
                                                 nameof(Object));

        /// <summary>
        /// Compares two values.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Int32 CompareTo(SensingStateType Value)

            => String.Compare(InternalId,
                              Value.InternalId,
                              StringComparison.Ordinal);

        #endregion

        #region IEquatable<SensingStateType> Members

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Object">A value to compare with.</param>
        public override Boolean Equals(Object? Object)

            => Object is SensingStateType value &&
                   Equals(value);

        /// <summary>
        /// Compares two values for equality.
        /// </summary>
        /// <param name="Value">A value to compare with.</param>
        public Boolean Equals(SensingStateType Value)

            => String.Equals(InternalId,
                             Value.InternalId,
                             StringComparison.Ordinal);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()

            => InternalId?.GetHashCode() ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return the text representation of this value.
        /// </summary>
        public override String ToString()

            => InternalId ?? "";

        #endregion

    }

}
