<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>cloud.charging.open.protocols.EEBus.SHIP</RootNamespace>
    <AssemblyName>cloud.charging.open.protocols.EEBus.SHIP</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Hermod\Hermod\Hermod.csproj" />
    <ProjectReference Include="..\..\Styx\Styx\Styx.csproj" />
  </ItemGroup>

</Project>
